### ISSUE TITLE
Windows contributors are required

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/gina.vim#1]
I don't have Windows so Windows contributors are required.

**Comment by bimlas** [comment]
I'll do what I can - the project seems promising.

**Comment by lambdalisue** [comment]
Cool! First of all, I don't know if the current version works on Windows. Could you test?

**Comment by bimlas** [comment]
It prints the output of the Git command: it works, but does not opening the Gina window, just echoing the results. Command-completion does not works. Before d02ea6b it opened up and the completing of the commands worked too, but it completed with the full path of the command, like `C:\users\me\.vim\plugins\gina.vim\autoload\gina\command\` if I hit `:Gina <C-D>`.

## Versions

Gina: 7b03a52
Windows 7: Vim 8.0.206

**Comment by bimlas** [comment]
I tried to run the tests (installed Themis) but a lot of those failed:

```
$ cd ~\.vim\plugins\gina.vim
$ themis.bat --reporter dot
```

The output contains a lot of

```
Vim(let):E117: Unknown function: vital#vital#import
```

Installed Vital, but it didn't solved the problem. I had to `set rtp+=path_to_vital` in *.themisrc*, than every tests became passed - it would be nice to warn the contributors in the help file about this. The output is:

```
***********************************************************
v:progname:     vim.exe
v:version:      800
has("lua"):     1
has("python"):  1
has("python3"): 1
$LANG:          HU
&encoding:      utf-8
&termencoding:  cp1250
&fileencodings: ucs-bom,utf-8,default,latin1
&fileformats:   dos,unix
&shellslash:    0
&runtimepath:
  c:/Users/nyolcas/.vim/plugins/vim-themis
  C:/Users/nyolcas/.vim/plugins/gina.vim
  C:\Users\nyolcas/vimfiles
  c:\app\vim/vimfiles
  c:\app\vim\vim80
  c:\app\vim/vimfiles/after
  C:\Users\nyolcas/vimfiles/after
  C:\Users\nyolcas/.vim/plugins/vital.vim
-----------------------------------------------------------
git version:     2.11.0
  worktree:      1
valid1:          C:\Users\nyolcas\AppData\Local\Temp\VIACA04.tmp\valid1
  develop            0be7be1 [ahead 1, behind 1] Second
  ext/master         6f7ad46 Fourth
* master             2a6a2ab Third
  remotes/ext/master 6f7ad46 Fourth
valid2:          C:\Users\nyolcas\AppData\Local\Temp\VIACA04.tmp\valid2
* develop            0be7be1 [ahead 1, behind 1] Second
  ext/master         6f7ad46 Fourth
  master             2a6a2ab Third
  remotes/ext/master 6f7ad46 Fourth
valid3:          C:\Users\nyolcas\AppData\Local\Temp\VIACA04.tmp\valid3
* master 6f7ad46 Fourth
invalid:         C:\Users\nyolcas\AppData\Local\Temp\VIACA04.tmp\invalid
***********************************************************
....................................................................................................................................................................
tests 164
passes 164
```

**Comment by lambdalisue** [comment]
Thanks a lot!

1. d02ea6b made things async. I'm planning to make commands sync again while I noticed that most of time I anyway need to wait the process end so it will be fixed I hope
2. Command completion is omitted for now while other features are fragile yet. I'll note these in README thanks
3. I removed dependency to vital.vim for test as well (not pushed yet). Thanks

**Comment by bimlas** [comment]
> does not opening the Gina window, just echoing the results

Still not working. To be sure, here's a screenshot of `Gina log %` on _travis.yml_:

![gina](https://cloud.githubusercontent.com/assets/7034200/22237048/940aa754-e209-11e6-943e-60e564230be5.png)

Tried out with minimal _.vimrc_ too.

**Comment by lambdalisue** [comment]
Got it. It seems gina.vim failed to load modules.

I changed the command loading strategy so could you try again? 1980548

**Comment by bimlas** [comment]
Tried on 6fec966: the window opens up, I can use the commands in it (`<Tab>` menu, mappings), command-completion works, created a commit, tests are passing expect one:

```
Failures:
  1) gina#util #open({uri}) calls "System.File.open()" to open {uri} with a system browser
     function themis/Runner.emit(name, ...) abort dict  Line:1  (~/.vim/plugins/vim-themis/autoload/themis/runner.vim)
     function 35(event, ...) abort dict  Line:3  (~/.vim/plugins/vim-themis/autoload/themis/emitter.vim)
     function themis#emitter#fire(listener, event, args) abort  Line:4  (~/.vim/plugins/vim-themis/autoload/themis/emitter.vim)
     function 26(event, args) abort dict  Line:5  (~/.vim/plugins/vim-themis/autoload/themis/runner.vim)
     function themis#emitter#fire(listener, event, args) abort  Line:2  (~/.vim/plugins/vim-themis/autoload/themis/emitter.vim)
     function themis/style['vimspec'].event.before_test(bundle, entry) abort dict  Line:1  (~/.vim/plugins/vim-themis/autoload/themis/style/vimspec.vim)
     function <SNR>12_call_hook(bundle, point) abort  Line:2  (~/.vim/plugins/vim-themis/autoload/themis/style/vimspec.vim)
     function 227() abort dict  Line:2  (~/AppData/Local/Temp/VILBC4C.tmp)
     function 411(path) abort dict  Line:1  (~/.vim/plugins/vim-themis/autoload/themis/helper/scope.vim)
     function <SNR>39_svars(path) abort  Line:1  (~/.vim/plugins/vim-themis/autoload/vital/_themis/Vim/ScriptLocal.vim)
     function <SNR>39_sid2svars(sid) abort  Line:4  (~/.vim/plugins/vim-themis/autoload/vital/_themis/Vim/ScriptLocal.vim)
     function <SNR>39_sid2path(sid) abort  Line:9  (~/.vim/plugins/vim-themis/autoload/vital/_themis/Vim/ScriptLocal.vim)
     function <SNR>39__throw(message) abort  Line:1  (~/.vim/plugins/vim-themis/autoload/vital/_themis/Vim/ScriptLocal.vim)
     
     vital: Vim.ScriptLocal: sid not found
```

`Gina log %` (on *README.md*) does not works, but did earlier - I can find the working commit if you need to know:
```
:Verbose Gina log %
not found in 'runtimepath': "autoload/vital/_gina/Argument.vim"
not found in 'runtimepath': "autoload/vital/_gina/Vim/Exception.vim"
not found in 'runtimepath': "autoload/vital/_gina/Vim/Buffer/Observer.vim"
not found in 'runtimepath': "autoload/vital/_gina/Git.vim"
not found in 'runtimepath': "autoload/vital/_gina/Action.vim"
not found in 'runtimepath': "autoload/vital/_gina/Data/Queue.vim"
process: git --no-pager -c core.editor=false -C C:\Users\Laci\.vim\plugins\gina.vim log .\README.md --color=always --graph --pretty=format:^[[32m%h^[[m - %s ^[[33;1m%cr^[[m ^[[35;1m<%an>^[[m^[[36;1m%d^[[m --
Error detected while processing function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync[1]..gina#core#process#call[16]..94[9]..91[1]..<SNR>73__job_callback[3]..99:
line    2:
E684: list index out of range: -1
Error detected while processing function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync[1]..gina#core#process#call[16]..94[9]..91[1]..<SNR>73__job_callback[3]..99:
line    5:
E684: list index out of range: -1
Error detected while processing function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync[1]..gina#core#process#call[16]..94[9]..91[1]..<SNR>73__job_callback[3]..99:
line    8:
E684: list index out of range: -1
Error detected while processing function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync[1]..gina#core#process#call[16]..94[13]..<SNR>73__ch_read_and_call_callbacks[9]..<SNR>73__job_callback[3]..98:
line    2:
E684: list index out of range: -1
Error detected while processing function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync[1]..gina#core#process#call[16]..94[13]..<SNR>73__ch_read_and_call_callbacks[9]..<SNR>73__job_callback[3]..98:
line    5:
E684: list index out of range: -1
Fail: git --no-pager -c core.editor=false -C C:\Users\Laci\.vim\plugins\gina.vim log .\README.md --color=always --graph --pretty=format:^[[32m%h^[[m - %s ^[[33;1m%cr^[[m ^[[35;1m<%an>^[[m^[[36;1m%d^[[m --
fatal: bad revision '.\README.md'
function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync, line 3
```
See `fatal: bad revision '.\README.md'`, the filename have to be after `--`.

`Gina log` hangs up on lambdalisue/gina.vim, but it works on bimlas/sandbox.

**Comment by lambdalisue** [comment]
> tests are passing expect one:

Could you give me more info for this? I could not find any unexpected code in the test and don't know why that fail.

> Gina log % (on README.md) does not works, but did earlier - I can find the working commit if you need to know:

Actually, the correct format is `Gina log -- %` while `git log` cannot distinguish a filename and a commit.

But

```
Error detected while processing function <SNR>46_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>72_exec_sync[1]..gina#core#process#call[16]..94[9]..91[1]..<SNR>73__job_callback[3]..99:
line    2:
E684: list index out of range: -1
```

is unexpected. Is this appear without `verbose`?

**Comment by bimlas** [comment]
> Could you give me more info for this?

I don't know why is this failing, I will look it for, but the `Gina browse` works as expected.

> the correct format is `Gina log -- %`

It works, showing the log of the file, but when I hitting `<CR>` on it it fails to open the commit and prints out the same message (with `Verbose`) if the file is in a subdirectory (*test\gina\util.vimspec*):

```
Error detected while processing function <SNR>255_BufReadCmd[1]..gina#core#process#exec[4]..<SNR>216_exec_sync[1]..gina#core#process#call[16]..384[13]..<SNR>217__ch_read_and_call_callbacks[9]..<SNR>217__job_callback[3]..388:
line    5:
E684: list index out of range: -1
Fail: git --no-pager -c core.editor=false -C C:\Users\Laci\.vim\plugins\gina.vim show :test\gina\util.vimspec --
fatal: bad revision ':test\gina\util.vimspec'
```

Tried out on command line, changing `\` to `/` in the file path solved the problem:

```
git --no-pager -c core.editor=false -C C:\Users\Laci\.vim\plugins\gina.vim show :test/gina/util.vimspec --
                                                                                     ^    ^
```

Actually I captured the the `E684: list index out of range: -1` with tpope/vim-scriptease plugin's `Verbose` command - with the native `verbose` it does not showing up. How can I capture the output in a more native way?

**Comment by lambdalisue** [comment]
> Tried out on command line, changing \ to / in the file path solved the problem:

Got it. I'll write a test for `Gina show` and fix this.

> How can I capture the output in a more native way?

I use `:Capture messages` command to put a result of `:messages` command into a buffer after `:verbose XXXXX`. (You may able to use it directly like `:verbose Capture Gina log -- %` but not 100% sure)

https://github.com/tyru/capture.vim

**Comment by bimlas** [comment]
It producing exactly the same output.

**Comment by bimlas** [comment]
Don't spend too much time on it: it may depend on other settings/system variables. It's maybe behaves in this way only on my computer, since all tests are passing on Appveyor, but not on my machine.

**Comment by lambdalisue** [comment]
I have not write a test but https://github.com/lambdalisue/gina.vim/commit/8364e9695bc678beacc81f757ecf8011c7663bfa would fix the problem that when you hit `<CR>` on a buffer which has shown by `Gina log -- %`

> It producing exactly the same output.

Hum... What was the exact procedure? I assumed

1. `:verbose Gina log -- %` on `<something>\gina.vim\README.md` file
2. `:Capture messages`
3. The output will be shown on a new buffer

> Don't spend too much time on it: it may depend on other settings/system variables. It's maybe behaves in this way only on my computer, since all tests are passing on Appveyor, but not on my machine.

Ok. Let me know if you find anything 👍

**Comment by bimlas** [comment]
I think this is caused by newly created buffer, but it's just a divining.

> `Gina log` hangs up on lambdalisue/gina.vim, but it works on bimlas/sandbox.

Still exists. It seems that it works with small repos, but hangs up on larger ones.

**Comment by lambdalisue** [comment]
> Still exists. It seems that it works with small repos, but hangs up on larger ones.

What did you mean by *hangs up* exactly? (e.g. Cursor doesn't move, The Window become white, etc.) Could you give me a screenshot?

**Comment by bimlas** [comment]
Here's a screencast: https://youtu.be/Dg1S83ajz68

**Comment by bimlas** [comment]
I waited five minutes in *hanged up* state, but still does nothing.

And forgot to add the version of Vim to video: 8.0.160

**Comment by lambdalisue** [comment]
Thanks. It seems really critical so I made a new issue #4

**Comment by lambdalisue** [comment]
@bimlas I sent a collaborator invitation to you. Accept it if you are welcome to test/fix behavior of gina.vim on Windows thanks 👍

**Comment by bimlas** [comment]
Cool! Thanks for the trust! :relaxed:

**Comment by lambdalisue** [comment]
:+1: Close this while it seems a core part of gina.vim is working on Windows
