### ISSUE TITLE
Blame in visual mode

### ISSUE THREAD

**Issue by ahmedelgabri** [lambdalisue/gina.vim#104]
I have question on why can't `:Gina blame` work in visual mode without specifying the line or column as stated here https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L1233-L1237

Sometimes I want to know who changed a couple of lines so I highlight them & check the blame, can this be done automatically with `gina` without the need to specify the number manually, can it pick up this info already from the visual selection?

**Comment by lambdalisue** [comment]
`--line` is a bit different. It specify the initial line.

I added code to use visual range as `-L` automatically

<del>https://github.com/lambdalisue/gina.vim/commit/6a435d77c13cf4346280e9149b934bc77142e5f7</del>

https://github.com/lambdalisue/gina.vim/commit/ca216e09deeb3a0fe3a1190acbf0b3f66495cca9

When you highlight the part of code, it produce a partial blame so that you git blame works pretty fast for huge file.

<img width="1920" alt="screen shot 2017-08-02 at 12 34 01" src="https://user-images.githubusercontent.com/546312/28856568-e872fdb8-777e-11e7-8c82-2734c14935b0.png">

**Comment by ahmedelgabri** [comment]
Great, thanks @lambdalisue!

**Comment by ahmedelgabri** [comment]
This is not working anymore.

![blame](https://user-images.githubusercontent.com/63876/31540601-67783888-b00c-11e7-8c50-5d3cd01f797c.gif)

**Comment by lambdalisue** [comment]
Well. I tried but it worked. Could you create a minimal vimrc to reproduce the issue?

**Comment by ahmedelgabri** [comment]
You are right, I tried with this minimal config & it works. Will try to find what is causing this issue then, sorry for the false alarm.

`~/minimal.vimrc`
```vim
set runtimepath+=~/.vim/plugged/gina.vim/
```

```
$ nvim -u ~/minimal.vimrc
```

**Comment by ahmedelgabri** [comment]
It's something here https://github.com/ahmedelgabri/dotfiles/blob/755d929f4716d417a142bd590ef4f439a2857d1b/vim/.vim/plugin/settings.vim do you have an idea which setting might be the issue?

If I comment out the whole file it works fine, I tried to comment out chunks of the file it didn't work. So I guess it might be a combination of two or more settings.

**Comment by ahmedelgabri** [comment]
I found the problem, it's _very surprisingly_ `set fileencoding=utf-8` but I dunno why it breaks the visual blame view

**Comment by lambdalisue** [comment]
Hum... Could you make a minimal vimrc if you think it's worth to investigate?

**Comment by ahmedelgabri** [comment]
Here is a minimal `.vimrc` that can reproduce the issue

```vim
set fileencoding=utf-8
set runtimepath+=~/.vim/plugged/gina.vim
```

**Comment by lambdalisue** [comment]
Thanks. I'll confirm it prob after vimconf2017

**Comment by lambdalisue** [comment]
I could not reproduce. Maybe https://github.com/lambdalisue/gina.vim/issues/129 fixed the issue somehow? Could you check?

I tried.

1. Write `minimal.vimrc` in `gina.vim` repository as

```vimrc
let s:root = expand('<sfile>:p:h')

set fileencoding=utf-8
execute printf('set runtimepath+=%s', s:root)
```

2. Open nvim with `nvim -u minimal.vimrc` in `gina.vim` repository
3. `:e README.md`
4. Visuall select some lines
5. `:'<,'>Gina blame`

**Comment by ahmedelgabri** [comment]
Yeah it seems to be working fine now, thanks 👍
