### ISSUE TITLE
stuck when cd to a git repository

### ISSUE THREAD

**Issue by tracyone** [lambdalisue/gina.vim#107]
This is a issue of macvim.

https://youtu.be/dLld3G6OWzo

I add following

> set status.="%{gina#component#repo#preset()}"

**reproduce step**

open macvim 

:cd to_any_git_repo

**macvim version**:

>  VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 25 2017 05:00:22)
MacOS X (unix) version
Included patches: 1-771
Compiled by travis@Traviss-Mac-645.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +comments        +extra_search    +jumplist        +mouseshape      +odbeditor       +scrollbind      +termresponse    +wildmenu
+arabic          +conceal         +farsi           +keymap          +mouse_dec       +packages        +signs           +textobjects     +windows
+autocmd         +cryptv          +file_in_path    +lambda          -mouse_gpm       +path_extra      +smartindent     +timers          +writebackup
+balloon_eval    +cscope          +find_in_path    +langmap         -mouse_jsbterm   +perl/dyn        +startuptime     +title           -X11
+browse          +cursorbind      +float           +libcall         +mouse_netterm   +persistent_undo +statusline      +toolbar         -xfontset
++builtin_terms  +cursorshape     +folding         +linebreak       +mouse_sgr       +postscript      -sun_workshop    +transparency    +xim
+byte_offset     +dialog_con_gui  -footer          +lispindent      -mouse_sysmouse  +printer         +syntax          +user_commands   -xpm
+channel         +diff            +fork()          +listcmds        +mouse_urxvt     +profile         +tag_binary      +vertsplit       -xsmp
+cindent         +digraphs        +fullscreen      +localmap        +mouse_xterm     +python/dyn      +tag_old_static  +virtualedit     -xterm_clipboard
+clientserver    +dnd             -gettext         +lua/dyn         +multi_byte      +python3/dyn     -tag_any_white   +visual          -xterm_save
+clipboard       -ebcdic          -hangul_input    +menu            +multi_lang      +quickfix        -tcl             +visualextra     
+cmdline_compl   +emacs_tags      +iconv           +mksession       -mzscheme        +reltime         +termguicolors   +viminfo         
+cmdline_hist    +eval            +insert_expand   +modify_fname    +netbeans_intg   +rightleft       +terminal        +vreplace        
+cmdline_info    +ex_extra        +job             +mouse           +num64           +ruby/dyn        +terminfo        +wildignore      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: 
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE

**Comment by lambdalisue** [comment]
I don't get what the problem. Could you explain it a bit more?

**Comment by tracyone** [comment]
@lambdalisue In macvim, setting statusline to %{gina#component#repo#preset()} will stuck macvim when cd to a git repo.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/gina.vim/commit/6cb386b3ee5731522e641ec126114ad0135fba28 would fix your problem and it is the only way to improve the performance.

While Vim does not have thread/coroutine, it is necessary to execute the code for the first time.
