### ISSUE TITLE
Gina status does not work when 'git config status.short true' is used

### ISSUE THREAD

**Issue by aiya000** [lambdalisue/gina.vim#110]
Hi.

On gina-status buffer.

--, ==, <<, and >> does nothing.

<Tab> shows completions, but I selected something, it does nothing :cry:  
echo is same.

On an unstaged file, I do `:Gina add %`, it doesn't work finely too.  
but it said `[gina] fatal: Invalid path '/Users': No such file or directory`.

- - -

This is my environment.

- Windows10 x86_64
- Kaoriya GVim 8.0.596

:D

**Comment by lambdalisue** [comment]
Let me know the values below in `gina://xxxxx:status` buffer

* `&shellslash`
* `gina#core#get()`
* `expand('%:p')`

Additionally, do you use `-s` option? If not, please try `:Gina status -s`. Also, it would be nice if I can see the entire contents of `gina://xxxxx:status`.

**Comment by aiya000** [comment]
@lambdalisue Sorry for your waiting :+1:

Sorry, below `myname`, `my-project`, and `MyProject` is fake texts.  
I'm hiding it. (it depends my working `x(`)  
But these are mostly same as real texts. (These are substituted by vim's `:s`)


- `&shellslash` is `1`
- `gina#core#get()` is `{'commondir': '', 'refname': 'my-project', 'worktree': 'C:/Users/myname/Desktop/git/my-project', 'repository': 'C:/Users/myname/Desktop/git/my-project/.git'} `
- `expand('%:p')` is `C:/Users/myname/Desktop/git/my-project/MyProject/MainWindow.xaml.cs`

I didn't use `-s`.  
I tried `:Gina status -s`, it worked correctly !

Also, below is a detail of `gina://my-project:status`.

```
## [32mmyname/mvvm-ize[m...[31morigin/myname/mvvm-ize[m [ahead [32m10[m]
 [31mM[m MyProject/MainWindow.xaml
```

**Comment by lambdalisue** [comment]
込み入ってきたので日本語で

1. Gina status -s だと動作したと言うことでしょうか？その場合 Gina status のパースに失敗している可能性が高いので -s 無しの Gina status の内容を教えて頂けると助かります（マズイところは1文字目以外を xxxxx 等して頂けると助かります）

2. ユーザー名の1文字目が特殊文字として認識されてしまう事が、Gina addが動作しない原因かと思っているのですが、ユーザーの最初は m で良いですか？

**Comment by aiya000** [comment]
- 1. はい、`:Gina status -s`は正しく動作しました。こんな感じです

```
## [32mixxxxxxxxxx/mvvm-ize[m...[31morigin/ixxxxxxxxxx/mvvm-ize[m
 [31mM[m Hxxxxxxxxx/Hxxxxxxxxx.csproj
 [31mM[m Hxxxxxxxxx/MainWindow.xaml
 [31mM[m Hxxxxxxxxx/MainWindow.xaml.cs
[31m??[m Hxxxxxxxxx/OnClosingWindowCommand.cs
```

- 2. Windowsユーザ名の最初の文字はiです！

**Comment by aiya000** [comment]
これはエスケープシーケンスが含まれていて、Vim上では正しく表示されています！

**Comment by lambdalisue** [comment]
あーなるほど。-s 付けなくてもショートで表示されてるんですね。確かに設定でやってる時の考慮を忘れてました、直します！

**Comment by lambdalisue** [comment]
@aiya000 修正しました。`Gina add %` が動かなかった？のは恐らく治っていません。
ただ、問題部分が別の気がするので、再現できたらお手数ですが別イシューを新たに作成お願いします（日本語で構いません）

**Comment by aiya000** [comment]
@lambdalisue ++  
このissueに関してはありがとうございます直っていました！  
Gina add %については[#112](https://github.com/lambdalisue/gina.vim/issues/112)を開きました xD
