### ISSUE TITLE
Better commit defaults

### ISSUE THREAD

**Issue by DerWeh** [lambdalisue/gina.vim#114]
I think that the `gina-commit` buffer should always `setlocal spell`. Additionally it should enter insert mode at the first line if there is no message so far.

I would also like to integrate [committia](https://github.com/rhysd/committia.vim) with `Gina commit` but so for I didn't succeed. Do you have an idea how to do this?

**Comment by lambdalisue** [comment]
You can use `gina#custom#execute()`  to execute commands on the buffer.

About commitia, you need to ask the plugin author while commitia seems to check the bufname (not sure).

**Comment by DerWeh** [comment]
Thanks I will look into `gina#custom#execute()`. I still think `spell` should be a default. 
Apparently I have problems with autocommands when it comes to `gina`. I already have one setting `spell` for every modifiable buffer, but it doesn’t work for the commit buffer.

`committia` uses
```
augroup plugin-committia
     autocmd!
     autocmd BufReadPost COMMIT_EDITMSG,MERGE_MSG if s:should_open('gitcommit') | call committia#open('git') | endif
 
     " ... Add other VCSs' commit editor filetypes
augroup END
```
for initialization. I tried adding one for `gina` like
```
autocmd BufReadPost gina://*:commit echom `test`
```
but the BufReadPost never triggers, while e.g. the `BufEnter` command triggers.

**Comment by lambdalisue** [comment]
> I still think spell should be a default.

No I don't. It should be up to the user. For example, without correct configuration, non English people would have a lot of spell errors on the buffer when they write them language.

> but the BufReadPost never triggers, while e.g. the BufEnter command triggers.

Currently `gina://xxxxxxx:commit` buffer does not call `BufReadPost`.
So use `gina#custom#execute()` instead for now.

**Comment by SevereOverfl0w** [comment]
Integration with Commita should be solved by using a filetype of `gitcommit` instead of gina-commit.

Is there a reason for custom filetype?

I have also run into integration issues for completion, and my ftplugin for gitcommit not being run.

**Comment by lambdalisue** [comment]
Because gina-commit buffer and gitcommit buffer is different.
If I use gitcommit instead, I have to consider all side effects which gina gives or takes and I don't want to take care about other plugins

**Comment by lambdalisue** [comment]
Hum. I noticed that ftplugin/gina-commit.vim does 'setlocal nospell' which I said should be up to user.
I'll remove that line

**Comment by lambdalisue** [comment]
btw, if you want, you can source ftplugin/gitcommit.vim by

runtime! ftplugin/gitcommit.vim
