### ISSUE TITLE
gina#component#repo#* doesn't returns a name properly after git-gc

### ISSUE THREAD

**Issue by tkfm-yamaguchi** [lambdalisue/gina.vim#118]
I noticed that `gina#component#repo#branch` returns just `'HEAD'` in some repositories even though `git rev-parse` and `git rev-parse --abbrev-ref HEAD` return a valid branch name.

After some investigation, I found that there are no `.git/ref/head/*` files in those repositories and such vanishment has caused by `git gc`.

So my question is: is it a feature/spec of gina that `gina#component#repo#branch` always returns 'HEAD' in the repository which `git gc` is executed, or are there any workaround for this?

**Comment by lambdalisue** [comment]
Thanks. Currently it's spec. However it sounds reasonable to implement a workaround for such situation.

Could you check if .git/packed-refs file has all requirements?

**Comment by tkfm-yamaguchi** [comment]
Thank you for the response!

> Could you check if .git/packed-refs file has all requirements?

Yes, `.git/packed-refs` contains a list of all refs and their hashes even after `git-gc` is executed in the repository. And, according to the document below, it seems to be assured that packed-refs has the informations about refs which the corresponding files don't exist in `refs/(heads|remotes|tags)/*`.

https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#_git_gc

**Comment by lambdalisue** [comment]
OK. I'll implement. Ping me when it seems I forgot about this issue

**Comment by tkfm-yamaguchi** [comment]
Sorry for responding late, and I can see the correct branch name in my status line after I updated gina today.

Thanks for your quick work !
