### ISSUE TITLE
`Gina browse` creates incorrect github url for branches

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#119]
For example on my repo, [async-clj-omni](https://github.com/clojure-vim/async-clj-omni).

1. `$ nvim README.md`
2. `:Gina show master:`
3. `:Gina browse --exact :`

Opens https://github.com/clojure-vim/async-clj-omni/blob/refs/remotes/origin/master/README.md which is a 404.

Also: using `:Gina browse` alone on `:Gina show master` file, opens https://github.com/clojure-vim/async-clj-omni/blob/a1772e906d70856dbb48385c66dfa14e099a8859/README.md. Which is an older version of the file (it isn't the same as the one I'm looking at!).

**Comment by lambdalisue** [comment]
Reproduced. Thanks I'll fix.

**Comment by lambdalisue** [comment]
Please confirm if your issue is solved via #121

**Comment by SevereOverfl0w** [comment]
Closer, but not entirely. I am now ending up at: https://github.com/clojure-vim/async-clj-omni/blob/origin/master/README.md#L8-L8 (it contains the remote name in the branch?)

**Comment by lambdalisue** [comment]
Hum. OK I'll check it with your repository.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/gina.vim/pull/121/commits/828d24be3bbd57bb50d0245b2c463a8fed373fb9

This should fix the issue. Could you confirm with the latest #121?

**Comment by SevereOverfl0w** [comment]
`:Gina browse :` now works, 🎉 This also fixed `--exact` too!

**Comment by lambdalisue** [comment]
Thanks. I'll merge it when #121 passed all tests (already failed one test on neovim 64 on Windows so I need to fix.

**Comment by lambdalisue** [comment]
Merged.
