### ISSUE TITLE
gina#component#repo#branch() errors out if the CWD is not a git directory

### ISSUE THREAD

**Issue by ahmedelgabri** [lambdalisue/gina.vim#120]
The gif will show:
- When I'm updating `vim-plug`
- opening a new file
- opening a current file  

All are from `$HOME` which is not a git repo of course.

![gina](https://user-images.githubusercontent.com/63876/30704296-90f64be4-9ef2-11e7-8137-72f23d768056.gif)

**Comment by lambdalisue** [comment]
Does `~/.git` exist somehow? It seems gina detect your home as a git repository

**Comment by ahmedelgabri** [comment]
You are right, I found a `~/.git` folder that was created by some vim plugin a while ago. Removed it & everything is working fine. Sorry for the false alarm & thanks for the help & the plugin :)
