### ISSUE TITLE
`:Gina commit` hangs, depending on GIT_EDITOR

### ISSUE THREAD

**Issue by ujihisa** [lambdalisue/gina.vim#122]
(今手元にarchlinuxないのであとで詳細加筆する)

## 問題

環境変数$GIT_EDITORが'gvim -g --servername=GVIM --remote-tab-wait-silent'とかになってる状態で`:Gina commit`すると固まる。

`<C-c>` すると復帰するが、↑のtabが開いて、さらに元のタブにginaのコミットのバッファもできてて、いちいちどちらかを閉じないといけなくて不便

なおこの環境変数はarchlinuxの場合vim起動すると勝手に定義されていた。具体的にどこで定義していて、どうやってdisableするかは未確認

## 解決

`:Gina commit` 時はGIT_EDITORを上書きしちゃうのがよさそう

**Comment by lambdalisue** [comment]
ありがとうございます。週末あたりに確認修正します。

**Comment by lambdalisue** [comment]
修正してみたので確認お願いします @ujihisa

**Comment by ujihisa** [comment]
ばっちりでした! 

![便利](https://pbs.twimg.com/profile_images/528913519563902976/H_uSpS56.png)
