### ISSUE TITLE
URL encode filepaths for use in browse

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#123]
For example, if current file open is `HELLO WORLD`, gina will generate `"https://github.com/user/repo/blob/master/HELLO WORLD"` instead of `"https://github.com/user/repo/blob/master/HELLO%20WORLD"`

**Comment by lambdalisue** [comment]
I see. It's not so difficuct while we have Web.URI module. I'll implement it on this weekend. Ping me if it seems I forgot about it
