### ISSUE TITLE
Reuse window when calling Gina status and others.

### ISSUE THREAD

**Issue by zzantares** [lambdalisue/gina.vim#125]
Hi, let me congratulate for this great plugin, I think it allows much more customization than others, I'm still checking the waters but so far so good. However I wonder how to instruct Gina to use the current window when calling functions like `status`, `commit`, `log`, etc. Because by default it always creates a split and I don't want that.

To explain further if I have no splits then I want Gina buffer to occupy the current window (somewhat like fullscreen), if I have splits then use the current window without creating new split window.

I read the help about the `--opener` but it seems the parameters it receives always results in splits, checking about `:help opening-window` does not mention an option to reuse a window. Of course in other cases like `blame` it makes sense that creates the split.

Is this possible?

Thanks!

**Comment by lambdalisue** [comment]
Try `--opener=edit`
Probably it is what you want 👍

**Comment by zzantares** [comment]
Yes that's it!

Thanks a lot 😃

**Comment by zzantares** [comment]
Hi again, I noticed a problem, now `:wq` does not performs the commit and makes vim close, I made a mapping to use `<C-s>` to `:w|bdelete` this stops vim from quit but commit does not happen. Perhaps I need to call a function in the mapping?

Thanks again!

**Comment by lambdalisue** [comment]
Currently, it is not possible to perform commit when Vim is closing. Additionally, the commit is performed on `QuitPre` so `:bdelete` won't work.

Alternative workaround is using `:Gina commit --opener=tabedit` instead.

**Comment by zzantares** [comment]
Ok that works, thanks!
