### ISSUE TITLE
Set modifiable when doing `:Gina compare :`

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#127]
This provides a two-way alternative to `:Gina patch`. It seems to work fine already, if I just jump into the special gina buffer and do `:set modifiable`

**Comment by lambdalisue** [comment]
Well. I don't really get what you want.

`:Gina compare :` opens

1. `gina://xxx:show/:yyy`
2. `yyy`

And `yyy` is already modifiable.

**Comment by SevereOverfl0w** [comment]
gina://xxx:show/:yyy wasn't modifiable when opened via compare. But is via patch.

On 29 October 2017 03:22:22 GMT+00:00, Alisue <notifications@github.com> wrote:
>Well. I don't really get what you want.
>
>`:Gina compare :` opens
>
>1. `gina://xxx:show/:yyy`
>2. `yyy`
>
>And `yyy` is already modifiable.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lambdalisue/gina.vim/issues/127#issuecomment-340234716

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lambdalisue** [comment]
I see. So you would like to patch in Gina compare interface.

Ideally, Gina compare is for comparing so I didn't make index buffer modifiable. So can I ask why Gina patch isn't enough for your situation?

**Comment by SevereOverfl0w** [comment]
It's sometimes _too much_ information to process. I can't see a diff of just what is and is not applied, I see diff across all three buffers.

I would be equally happy with an option flag to patch which only shows two buffers (and closes an open one if already exists). This would be useful for toggling between the two modes if done this way.

On 29 October 2017 20:25:46 GMT+00:00, Alisue <notifications@github.com> wrote:
>I see. So you would like to patch in Gina compare interface.
>
>Ideally, Gina compare is for comparing so I didn't make index buffer
>modifiable. So can I ask why Gina patch isn't enough for your
>situation?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lambdalisue/gina.vim/issues/127#issuecomment-340291413

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lambdalisue** [comment]
Got it. I'll prob. add some option to Gina patch

**Comment by lambdalisue** [comment]
Done. You can use

1. `:Gina patch --oneside` command
2. `patch:onside` action

**Comment by SevereOverfl0w** [comment]
Just gave it a quick go, that's great, thanks!

**Comment by lambdalisue** [comment]
> and closes an open one if already exists)

oops, it is not implemented yet
