### ISSUE TITLE
How to suppress the message of Gina reset

### ISSUE THREAD

**Issue by wsdjeg** [lambdalisue/gina.vim#132]
every time I run `Gina reset %` , I see

```
[gina] Unstaged changes after reset:                                                                                                                   
[gina] M        autoload/SpaceVim/layers/VersionControl.vim
Press ENTER or type command to continue
```

and it will block my vim, until I press enter, it can not be used in other scripts.

**Comment by lambdalisue** [comment]
I think one of the followings are enough

1. `:Gina reset -q %`
2. `:silent Gina reset %`

**Comment by wsdjeg** [comment]
@lambdalisue I just have a try with both, both of them will popup a `Press ENTER or type command to continue` in neovim.

I recommend gina echo message line by line, and before echo a message, just use ` echon "\r\r"` to clear the cmdline or use `redraw!`.

**Comment by wsdjeg** [comment]
here is the link for this issue https://asciinema.org/a/Rnn3SMkzF6kfqF9wAaMutGJtN


EDIT:

I just have a try with `Gina reset -q` it works well, but it will output nothing, I do not know if the command run successfully, I hope gina do not block vim with `Press ENTER or type command to continue`

**Comment by wsdjeg** [comment]
sorry, `Gina reset -q` is what I want.

**Comment by lambdalisue** [comment]
I'm sorry I could reproduce it with minimal vimrc. I didn't noticed while the above two works on my environment. It seems a bug.

**Comment by lambdalisue** [comment]
OK. Now both should work now

f4920ceb777f9a4e882f51078ea3f8579bff03fb
069bc3576d574d8fc9e1fd97da5b2b1a53529665

**Comment by wsdjeg** [comment]
yeah it has been fixed。 but is there an option for simple message output and without pause?

**Comment by lambdalisue** [comment]
See `:help more`

**Comment by wsdjeg** [comment]
@lambdalisue I know there is a `more` for this issue, but this options will disable all the pause when echo message, but what I need is just for this plugin, I just try to wappr command,

```
 let save_more = &more
 set nomore
 Gina {cmd}
 let &more = save+more
```

but as Gina is async plugin, this wapper does not work.

**Comment by lambdalisue** [comment]
In this case, you can use gina's event system (private API) like

```
function! s:on_command_called_raw(scheme) abort
  if exists('s:saved_more')
    let &more = s:saved_more
  endif
endfunction

call gina#core#emitter#subscribe('command:called:raw', function('s:on_command_called_raw'))

function! CallGinaSilently(args) abort
  let s:saved_more = &more
  set nomore
  execute 'Gina' a:args
endfunction
```

See `:help gina-dev-events` for detail.

**But I don't recommend you to touch `more`**. 

1. Any messages comes from other plugins or whatever would be affected as well
2. Users may execute `set nomore` during `:Gina reset` and it could not be restored.

I think users should know about `more` and let users to touch but If you desire, please make a new issue as a feature request then I'll condsider a better way:+1:
