### ISSUE TITLE
Discard action can erase entire directory if unstaged filename contains '<>'

### ISSUE THREAD

**Issue by mkrawiec** [lambdalisue/gina.vim#133]
Sooo, I had a very stressful morning today when I found that 'discard' action from status window deleted my entire local repository (luckily I had my work loaded in the buffers so little harm was done)

Here's what happened - I had to discard a file named `<Plug>_` which is a junk file created by some other of my installed plugins and it turns out that the filename was problematic to say the least.

I've located the issue in the function `gina#core#path#abspath` but my knowledge of vimscript is not sufficient to fix this bug

    :echo gina#core#path#abspath('Test_')
    /home/user/gina_test/Test_ (correct)

    :echo gina#core#path#abspath('<Plug>_')
    /home/user/gina_test/ (repository root)

This is then feeded to the rm command

Hope this helps to track down the problem further, thanks!

**Comment by lambdalisue** [comment]
Wow. That's really bad. I'll fix asap

**Comment by lambdalisue** [comment]
Should be fixed. I'm sorry for your data lost...

**Comment by mkrawiec** [comment]
Thanks, I'll test. Keep up your great work, this plugin is awesome.
