### ISSUE TITLE
Test fail on neovim HEAD

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/gina.vim#135]
https://github.com/neovim/neovim/pull/6844
https://ci.appveyor.com/project/lambdalisue/gina-vim/build/655/job/brq82xko9xudoi8p#L115
https://travis-ci.org/lambdalisue/gina.vim/jobs/308500736#L2077

**Comment by wsdjeg** [comment]
I get same issue with my own config.

https://github.com/wsdjeg/DotFiles/blob/master/SpaceVim.d/init.vim#L125

fixed by add some check. but I think neovim's job stdout has been changed.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/gina.vim/blob/master/test/gina/process.vimspec#L31

The implementation used in a test is not well designed so I need to fix.

**Comment by lambdalisue** [comment]
@wsdjeg 

Yes. It use channel internally now.
https://github.com/neovim/neovim/pull/6844

**Comment by wsdjeg** [comment]
@lambdalisue Thanks for these info, so there ars some changes after this PR? is there a check er for neovim to judge it?

as I know this PR add some new functions, so can we use

```vim
   if exist('*new_func_name')
       " old stdout handle func
   else
      " new fixed stdout handle func
   endif
```

sometimes I need to use old version of neovim.

**Comment by lambdalisue** [comment]
fixed.
