### ISSUE TITLE
`scrolloff=9999` makes `Gina blame` unusable when used in middle of the file.

### ISSUE THREAD

**Issue by hauleth** [lambdalisue/gina.vim#137]

**Comment by lambdalisue** [comment]
Could you write the detail? I cannot get what the problem is from an empty description.

**Comment by hauleth** [comment]
I will prepare example repo and ASCIICast when I get to my workplace. 

--
Łukasz Jan Niemier

**Comment by hauleth** [comment]
Ok, I cannot reproduce it right now. Closing till it happen again.

**Comment by hauleth** [comment]
There is an AsciiCast of the issue.

https://asciinema.org/a/knONOKFFx7nmlyVSQiuZD0tOL

It can be fixed by setting `set scrolloff=0` however I would prefer not to.

EDIT:

I have bisected it and it seems to happen (with `scrolloff=99`) when there is less than 71 lines till the end of file in file with 179 lines and less than 49 lines in file with 74 lines. I cannot find the pattern though.

**Comment by lambdalisue** [comment]
Ok. I'll confirm thanks :+1:

**Comment by lambdalisue** [comment]
Well. I cannot reproduce the issue (and actually I still don't get what the problem here.)

Please describe the detail with words. AsciiCast is too fast and I don't get what is happening there.

Additionally, it would nice if you could prepare the minimum vimrc to reproduce the situation
