### ISSUE TITLE
'Gina stash save' executes command included custom command options

### ISSUE THREAD

**Issue by notomo** [lambdalisue/gina.vim#146]
# Problems summary
When custom command options set(ex. --opener="vsplit"),
'Gina stash save "foo"' executes 'Gina stash save foo --opener=vsplit'.
As a result I get a stash named "foo --opener=vsplit".

## Expected
I get a stash named "foo".

## Environment Information
- gina.vim version(SHA1): 04d7983
- OS: centos7
- Vim/neovim version: v0.2.3-1676-gbc17ad3

## minimal init.vim
```
set runtimepath+=~/.vim/dein/repos/github.com/lambdalisue/gina.vim/
edit ~/.vim/dein/repos/github.com/lambdalisue/gina.vim/README.md
call gina#custom#command#option('stash', '--opener', 'vsplit')
```

## The reproduce ways from neovim starting 
1. Save changes in a git repository
2. Execute :Gina stash save "foo"
3. Execute :Gina stash list

**Comment by lambdalisue** [comment]
Got it but I need to think the way to solve this.

For now, you can make an alias and assign the option to the alias. Aliases and command itself have different option space.

**Comment by notomo** [comment]
```
call gina#custom#command#option('stash', '--opener', 'topleft split')
call gina#custom#command#alias('stash', 'stash_for_save')
execute 'Gina stash_for_save save "foo"'
```
Thank you for your answer! This is enough to solve my problem for now.
