### ISSUE TITLE
'changes:of' action doesn't show changes of the commit

### ISSUE THREAD

**Issue by notomo** [lambdalisue/gina.vim#147]
# Problems summary
'changes:of' action's result seems to be the same as 'changes:between'.

## Expected
The result is the same as 'git diff {revision}^..{revision}'
(But this can't with initial commit.)

## Environment Information
- gina.vim version(SHA1): 04d7983
- OS: centos7
- Vim/neovim version: v0.2.3-1676-gbc17ad3
- git version 2.15.0

## minimal init.vim
```
set runtimepath+=~/.vim/dein/repos/github.com/lambdalisue/gina.vim/
edit ~/.vim/dein/repos/github.com/lambdalisue/gina.vim/README.md
```

## The reproduce ways from neovim starting 
1. Execute :Gina log
2. Move to '3d59045'
3. Execute 'changes:of' action
4. Confirm existing changes except for 'autoload/gina/command/qrep.vim'

**Comment by lambdalisue** [comment]
Thanks. I'll confirm :+1:

**Comment by lambdalisue** [comment]
Confirmed but it is not a bug (`changes:of` is equivalent to `git diff {revision}` in current definition). 

However, I like your idea and I don't think the current definition is useful. So I would love to change the definition of `changes:of` action when I got time thanks 👍
