### ISSUE TITLE
Gina shows 'enter passphrase' when the key has passphrase

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/gina.vim#148]
When SSH key file has a passphrase, it shows `'enter passphrase'` and gina cannot handle it.

**Comment by lambdalisue** [comment]
I'm not sure if it can be fixed...

**Comment by ulidtko** [comment]
I think: not really, Vim shouldn't handle this. (Does vim have any modal dialogs?..)

The standard workaround is:
 * `eval $(ssh-agent)`
 * `ssh-add ~/.ssh/my_private_key.id_rsa`
   +  enter key decryption password if needed
 * `ssh-add -l` to verify the key has been loaded into ssh-agent
 * any ssh/git operations using that key, should work without password prompts.
