### ISSUE TITLE
Use --abbrev-commit instead

### ISSUE THREAD

**Issue by tracyone** [lambdalisue/gina.vim#158]
function `gina#component#repo#branch()` return **current branch name** or **commit id** if your repo is in detached status.

In the case of **commit id**, it is too long

**Comment by lambdalisue** [comment]
Implemented by https://github.com/lambdalisue/gina.vim/commit/ca5802b2c8e598fd936f4665dfed6d97f987842d

**Comment by tracyone** [comment]
thanks for your work
