### ISSUE TITLE
How to commit part of a file?

### ISSUE THREAD

**Issue by semanser** [lambdalisue/gina.vim#162]
Is there are any way to commit not the whole file, but some selected lines?

**Comment by lambdalisue** [comment]
Try 'Gina patch %' or 'pp' on gina-status

**Comment by semanser** [comment]
Yes, this helped, thanks. It opens three separate buffers but to tell truth I can not figure out how to use that. Documentation does not help :(

**Comment by lambdalisue** [comment]
The middle one is the content in your index. So what you need is quite simple, modify the middle one as you want and save it. Then the changes are patched.

**Comment by semanser** [comment]
@lambdalisue Awesome! it works well :) But for what is the first and the last buffers?

**Comment by lambdalisue** [comment]
https://asciinema.org/a/L3PV4u8CsmeqEcyX6vpDK1Y0w

**Comment by lambdalisue** [comment]
> But for what is the first and the last buffers?

Left one is the content of HEAD and the right one is the content in your working tree.
You can compare the difference among HEAD, INDEX, and working tree.

Additionally, you can use

- `dol` - Obtain changes around the cursor from Left (HEAD)
- `dor` - Obtain changes around the cursor from Right (Working tree)
- `dp` - Put changes around the cursor to Right (Working tree)

mappings. As I used in the asciinema

**Comment by semanser** [comment]
Now it all makes sense for me, thank you! The last question: my splits are horizontally divided, but your opens in vertical mode. How to make them vertical?
![2018-04-02 17 03 58](https://user-images.githubusercontent.com/4020045/38199063-efa49956-3697-11e8-8da7-4dd2ad61b985.png)

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L1631

I'm sorry for that it's a bit difficult to find this line. In short, add the followings

```vim
set diffopt+=vertical
```
