### ISSUE TITLE
if $LANGUAGE is not en_US:en, `--  : toggle` can't work

### ISSUE THREAD

**Issue by fcying** [lambdalisue/gina.vim#172]
if $LANGUAGE not set to  `en_US:en`, `git status` not display english, `--  : toggle` can't work

**Comment by lambdalisue** [comment]
I have no idea what `-- : toggle` is. Could you explain the situation a bit more?

**Comment by fcying** [comment]
from Usage: general working-flow
```
:Gina status             │ <<  : stage
   │     │          │       │ >>  : unstage
   │     │          │       │ --  : toggle
```

if `:Gina status` not displayed by using english, the  shortcut key `<<  : stage` `>>  : unstage`  `--  : toggle` can not work.

**Comment by lambdalisue** [comment]
Got it. It seems https://github.com/lambdalisue/gina.vim/issues/159 is a related issue.

I'll check it at the weekend but which `$LANGUAGE` do you use? Could you paste the screenshot?

**Comment by lambdalisue** [comment]
A rejected PR (https://github.com/lambdalisue/gina.vim/pull/160) may fix your issue while it forced to use English for parsing.
I restored that branch and PR so could you try that one in case? (The version of gina in that PR is quite old though)

**Comment by fcying** [comment]
My `$LANGUAGE` is `zh_CN:zh`, Gina status:
```
位于分支 master                                                                                                                                                                             
您的分支与上游分支 'origin/master' 一致。
尚未暂存以备提交的变更：
  （使用 "git add <文件>..." 更新要提交的内容）
  （使用 "git checkout -- <文件>..." 丢弃工作区的改动）

    修改：     etc/zshrc

修改尚未加入提交（使用 "git add" 和/或 "git commit -a"）
```
I apply the #160 PR, Gina status will displayed by english, and then  the shortcut key can work .
Gina status:
```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   etc/zshrc

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by lambdalisue** [comment]
@fcying The #160 is too old to apply in the latest gina. I create a new PR #173 so could you try?

**Comment by fcying** [comment]
work fine by use branch fix-lang
