### ISSUE TITLE
View changes of a commit in git blame

### ISSUE THREAD

**Issue by huyvohcmc** [lambdalisue/gina.vim#184]
Is it possible to view only changes (`diff`) of a commit in `Gina blame` instead of the whole state of the file at that commit?

**Comment by lambdalisue** [comment]
<img width="1481" alt="1 nvim 2018-11-25 00-27-03" src="https://user-images.githubusercontent.com/546312/48969916-d82dec80-f048-11e8-9305-c67f3e3b50de.png">

I may not get it correct but do you mean something like above? Then use `show:commit` action (above use `show:commit:top`)
