### ISSUE TITLE
Unintended diff mode is started

### ISSUE THREAD

**Issue by notomo** [lambdalisue/gina.vim#191]
# Problems summary
If the diff mode buffers exist for each of `a_file` and `b_file`,
to open them in the same tab causes an unintended diff mode.

## Expected
An unintended diff mode is not started.

## Environment Information
* gina version (SHA1): e0e40fa
* OS: CentOS7
* neovim `:version` output:
```
NVIM v0.3.2-1051-g4a7f6dafe
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-102f1ba6-9808-43b7-aed2-685999d1d346

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

## a minimal init.vim

```vim
let s:path_to_gina = '~/.vim/minpac/pack/minpac/start/gina.vim'
execute 'set runtimepath+=' . s:path_to_gina
execute 'cd ' . s:path_to_gina
source ./plugin/gina.vim " ?

Gina compare :.appveyor.yml
Gina compare :.codecov.yml
tabe .codecov.yml
split .appveyor.yml
```

## How to reproduce the problem from neovim startup
1. nvim -u path/to/minimal_init.vim

## Memo
- https://github.com/lambdalisue/gina.vim/blob/e0e40fafc63451b411988ef0a44b043f8d4d5bf2/autoload/gina/util.vim#L165
Can I solve this issue by adding a check whether the buffers should be diff?

**Comment by lambdalisue** [comment]
Probably related to https://github.com/vim/vim/pull/2394

In short, add `set diffopt+=hiddenoff` to your vimrc.

**Comment by notomo** [comment]
Thank you for your advice!
But `set diffopt+=hiddenoff` did not resolve this issue. 😢
Probably it is because the buffers are not hidden.
In the first place, `hidden` remains the default value in the minimal init.vim.

- minimal init.vim
```
set diffopt+=hiddenoff
let s:path_to_gina = '~/.vim/minpac/pack/minpac/start/gina.vim'
execute 'set runtimepath+=' . s:path_to_gina
execute 'cd ' . s:path_to_gina
source ./plugin/gina.vim " ?

Gina compare :.appveyor.yml
Gina compare :.codecov.yml
tabe .codecov.yml
split .appveyor.yml
```

**Comment by lambdalisue** [comment]
#192 may solve your issue. Could you try?

**Comment by notomo** [comment]
Thank you!
It works as expected.😄

**Comment by lambdalisue** [comment]
The change would affect the current behavior so I'll test that branch by my self at least one week. I'll merge it then. Ping me if I forgot. 👍

**Comment by notomo** [comment]
Thank you for fixing!
