### ISSUE TITLE
add action for showing all branches

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#196]
Is it possible to add `branch:all` action that does `:Gina branch --all`. Most of the time I start with `:Gina branch`. I then realize that my remote branch doesn't have a local branch yet. So I need to quit and start `:Gina branch -a` again.

I would want this to be supported.

```
:Gina branch
a          (action)
branch:all
```

**Comment by lambdalisue** [comment]
It's possible but I think you don't need action.

Add the following to use `--group` option on `:Gina branch`

```vim
call gina#custom#command#option(
      \ 'branch', '--group', 'gina-branch',
      \)
```

Then try

```
:Gina branch --opener=split
:Gina branch --opener=split -a
```
