### ISSUE TITLE
Return to previous code buffer after status / commit / push

### ISSUE THREAD

**Issue by devth** [lambdalisue/gina.vim#208]
I typically use status, commit, then push. This leaves the status after push succeeds. Could it auto return to the code buffer that it replaced instead?

**Comment by lambdalisue** [comment]
Unfortunately no. But I guess you can use `<C-o>` to go back manually and it's enough isn't?

**Comment by devth** [comment]
After status + commit + push plus moving within those buffers I have to hit `<C-o>` quite a few times. Maybe I'll just use `:new` before I interact with Gina.

**Comment by lambdalisue** [comment]
Or

1. Add mark before (it's quite common for any Vim operation)
2. Use `:Gina status --opener=new` to open a status in a new buffer

**Comment by devth** [comment]
`:Gina status --opener=new` is working well. Thanks.
