### ISSUE TITLE
Error when trying to exit and commit in the commit buffer

### ISSUE THREAD

**Issue by resolritter** [lambdalisue/gina.vim#211]
![image](https://user-images.githubusercontent.com/17429390/58431126-c7efdc00-8082-11e9-98a5-05ce2cd42440.png)

On the stop split I have: `Gina diff HEAD`
On the bottom split I have: `Gina commit`

I was trying to close and commit the `Gina commit` bottom split, then this error came up

**Comment by lambdalisue** [comment]
I haven't seen this message. Could you write a vimrc and steps to reproduce this error?

**Comment by resolritter** [comment]
Thank you for the response and the work in this plugin @lambdalisue! The truth is, I don't know how to exactly reproduce this issue because it was the first time that happened to me too. I just posted the exception there in hopes you could intuit what was going wrong - it seems to be something related to getting the current file name for the split.

I'll do some more investigation and see if I can solve this one. The function where the exception was raised is: https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/command/commit.vim#L300

**Comment by lambdalisue** [comment]
I see. Well then, it's quite difficult to fix. I keep this issue open to getting more information from people who suffer this issue as well. 👍

**Comment by lambdalisue** [comment]
**Please put :+1: to the issue if you suffer this issue as well at least.**
I would like to know at least if this issue is rare or not.

Well of course, more deep investigations are always welcome. 👍
