### ISSUE TITLE
Gina blame is blocking

### ISSUE THREAD

**Issue by ghost** [lambdalisue/gina.vim#214]
It seems `Gina log` can fetch the log lazily, so perhaps `Gina blame` could use a similar principle. Did you have any plans for this?

**Comment by lambdalisue** [comment]
Unfortunately no. Gina blame does a lot of calculation or whatever which require entire content.

**Comment by ghost** [comment]
I ran into a similar problem with gitea, and found out about an attempt to fix those very heavy git operations which must walk the entire log to terminate. Take a look, it would be interesting for Gina. https://devblogs.microsoft.com/devops/supercharging-the-git-commit-graph/
