### ISSUE TITLE
bufhidden=delete for index/special buffers?

### ISSUE THREAD

**Issue by blueyed** [lambdalisue/gina.vim#215]
When using `cc` from `:Gina status`, it opens a diff against the index (`gina:/neovim:show/:foo`).

From vim-fugitive I'm used that closing the buffer with the file in the index will ask for it being saved (if modified), which is achieved via setting `bufhidden=delete` for it.

I think that might be useful in general for special, modifiable buffers.

btw: there might be some bug there, because later the (index) buffer was not modifiable anymore (when doing `cc` again) (`Last set from ~/.dotfiles/vim/plugged/gina.vim/autoload/vital/_gina/Vim/Buffer/Writer.vim`).

**Comment by lambdalisue** [comment]
Could you show some ideal behavior example screencast or whatever? I couldn't image the behavior.

> btw: there might be some bug there, because later the (index) buffer was not modifiable anymore (when doing cc again) (Last set from ~/.dotfiles/vim/plugged/gina.vim/autoload/vital/_gina/Vim/Buffer/Writer.vim).

New issue with step by step procedure would be really welcome 👍

**Comment by blueyed** [comment]
It was just a drive-by issue created from when trying gina - I am still using fugitive by default - just some suggestion.
Feel free to close it.
