### ISSUE TITLE
`:Gina status` throws "E688: More targets than List items" error

### ISSUE THREAD

**Issue by daveyarwood** [lambdalisue/gina.vim#218]
I noticed recently that this error tends to appear the first time I run `:Gina status` during a Vim session.

![2019-07-12-094245_1544x94_scrot](https://user-images.githubusercontent.com/4909079/61132606-ba06e680-a489-11e9-9d0f-c3091bd926c3.png)

Every time I run `:Gina status` after that, it works fine. The error only happens the first time I run it after opening Vim.

**Comment by lambdalisue** [comment]
Thanks. Could you tell me your OS and Vim version (Vim or Neovim?) to reproduce the error?

**Comment by daveyarwood** [comment]
I'm using Ubuntu 16.04, with Neovim from the unstable PPA.

```
$ apt-cache policy neovim
neovim:
  Installed: 0.4.0+ubuntu3+git201907111108-777cc6f-f1ec5d7-d4d251e~ubuntu16.04.1
  Candidate: 0.4.0+ubuntu3+git201907132023-6f944d3-f1ec5d7-d4d251e~ubuntu16.04.1
  Version table:
     0.4.0+ubuntu3+git201907132023-6f944d3-f1ec5d7-d4d251e~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial/main amd64 Packages
 *** 0.4.0+ubuntu3+git201907111108-777cc6f-f1ec5d7-d4d251e~ubuntu16.04.1 100
        100 /var/lib/dpkg/status
```

**Comment by lambdalisue** [comment]
I could not reproduce the issue but tried to fix so could you try #221?

**Comment by daveyarwood** [comment]
I actually can't repro the issue anymore on master... I did update my vim plugins and apt packages (including Neovim) the other day, so I suspect that some underlying issue may have been fixed in Neovim.

My Neovim version is now:

```
$ apt-cache policy neovim
neovim:
  Installed: 0.4.0+ubuntu3+git201907152022-5193826-f1ec5d7-d4d251e~ubuntu16.04.1
  Candidate: 0.4.0+ubuntu3+git201907152022-5193826-f1ec5d7-d4d251e~ubuntu16.04.1
  Version table:
 *** 0.4.0+ubuntu3+git201907152022-5193826-f1ec5d7-d4d251e~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by lambdalisue** [comment]
Ok 👍
