### ISSUE TITLE
Gina status: jump to next/previous item

### ISSUE THREAD

**Issue by AndreGeng** [lambdalisue/gina.vim#219]
within Gina status buffer, is there a way to jump to next/previous item, like Ctrl-n/Ctrl-p works within :Gstatus buffer in fugitive.vim

**Comment by olmokramer** [comment]
You can use Vim's builtin `[c` and `]c`.

**Comment by AndreGeng** [comment]
actually [c and ]c are not working for me. From my understanding these two shortcuts is using to jump between file changes. But they are not working in :Gina status view. What I am asking is jumping inside status view as following pic shows
![image](https://user-images.githubusercontent.com/3634890/61192241-99d36380-a6e5-11e9-91f2-05ca6aa0fd48.png)
quickly jump to the changed file item.

**Comment by lambdalisue** [comment]
Unfortunately there are no exact equivalent. But you can quickly check the difference or whatever with action & dot repeat like

```
:Gina status -s
a  <- Open action window
show:preview:top<CR>  <- Execute 'show:preview:top' action
j.  <- Repeat the previous action with next item
j.  <- ... and next
j.  <- ... and next
```

and if you desire, you can get similar behavior with the following (note that you must use `:Gina status -s` for below)

```vim
call gina#custom#mapping#nmap('status', '<C-n>', 'j<Plug>(gina-show-preview)')
call gina#custom#mapping#nmap('status', '<C-p>', 'k<Plug>(gina-show-preview)')
```

**Comment by olmokramer** [comment]
@AndreGeng Oh right, seems I misunderstood the question.

**Comment by AndreGeng** [comment]
@lambdalisue thanks for the reply, "Gina status -s" should works for me currently.
