### ISSUE TITLE
:Gina patch buffer, how to stage lines instead of stage hunk

### ISSUE THREAD

**Issue by AndreGeng** [lambdalisue/gina.vim#220]
within :Gina patch buffer, is there a way to stage visually selected lines instead of stage the whole hunk?

**Comment by olmokramer** [comment]
You can run `:diffput` on the selected lines. This won't work with `:diffget`, though, because you can't select "deleted" lines.

**Comment by AndreGeng** [comment]
@olmokramer thanks for ur reply.  I didn't know this before :)
