### ISSUE TITLE
no-color option of git does not work

### ISSUE THREAD

**Issue by yassu** [lambdalisue/gina.vim#224]
If we run `Gina log --no-color`, we have following output (with `syntax off` or `syntax on`).

I think that `--no-color` option does not work.
I would expect that only white charactors are output when `--no-color` option is set.

<img width="1213" alt="スクリーンショット 2019-08-22 19 00 56" src="https://user-images.githubusercontent.com/6589590/63505974-83ec6600-c50f-11e9-9d13-1e6b02753479.png">
<img width="873" alt="スクリーンショット 2019-08-22 19 00 01" src="https://user-images.githubusercontent.com/6589590/63505997-936baf00-c50f-11e9-86cb-f993bf5c1dba.png">

**Comment by lambdalisue** [comment]
Gina requires ANSI escape sequence to parse the output so `--no-color` is not applied.
