### ISSUE TITLE
Gina commit not working on windows

### ISSUE THREAD

**Issue by K1DV5** [lambdalisue/gina.vim#229]
I made some changes, entered `Gina status`, and used `--`  to stage my changes and when I tried `Gina commit`, it gives me this error:
```
[gina] Fail: git --no-pager -c core.editor=false -c color.status=always -C D:\git\repo\path commit --edit
[gina] error: There was a problem with the editor 'false'.
[gina] Please supply the message using either -m or -F option.
```

**Comment by lambdalisue** [comment]
Could you tell me your git version, vim or neovim version?

**Comment by K1DV5** [comment]
git version 2.23.0.windows.1
neovim 0.4.2

**Comment by wsdjeg** [comment]
@lambdalisue as I remember, it works well in old version of gina an git.

**Comment by lambdalisue** [comment]
> @lambdalisue as I remember, it works well in old version of gina an git.

Yes. Prob the version of git is the matter but I'm not sure while I don't use Windows....

**Comment by wsdjeg** [comment]
Is there any update on this issue, I hope this plugin can be used in windows.

**Comment by K1DV5** [comment]
Not so far, there are other issues as well.

**Comment by lambdalisue** [comment]
I'm not sure but maybe `false` is not a valid program on Windows and newer git complain that.
What happens if you provide `false.bat` which **always** exit with 1 on your `PATH`?

**Comment by K1DV5** [comment]
Tried using a `false.bat` which exits with both 1 and 0 but it still fails with the same message. Maybe the issue is not related with it.

**Comment by lambdalisue** [comment]
Prob fixed. Please try @K1DV5 @wsdjeg

**Comment by ghost** [comment]
I checked working well on Windows neovim !

**Comment by K1DV5** [comment]
Yes, problem fixed, good job!!
