### ISSUE TITLE
Disable periodic checking

### ISSUE THREAD

**Issue by K1DV5** [lambdalisue/gina.vim#233]
Sorry if this is in the docs and I missed it. What I noticed is that gina periodically runs git in the background (async) so that maybe changes to files are reflected in `gina status` buffers? This makes my machine seem doing a lot of work so I was wondering if there was a way to disable that. I'm OK reopening the `gina status` buffer when there are changes. I think fugitive works this way.

**Comment by lambdalisue** [comment]
Try `set noautoread`. I think I put code to check the value of `autoread` to enable that feature.

**Comment by K1DV5** [comment]
I tried that, same thing happens. And I think checking for a global config variable would be better, like `g:gina#auto_update` or something.

**Comment by lambdalisue** [comment]
I'll work on it prob on this weekend :+1:

**Comment by K1DV5** [comment]
Fixed. Thanks.
