### ISSUE TITLE
Gina status not working as expected

### ISSUE THREAD

**Issue by K1DV5** [lambdalisue/gina.vim#234]
Typing `--` in a `Gina status` buffer toggles the staging status of the file under the cursor (as it should) but it does not update the status buffer. When I reopen the status buffer, I get the updated status, so I know it does the git command in the background. It just has to update the status buffer.

And the `<<` map does not work, it gives the error `E21: Cannot make changes, 'modifiable' is off` as if I tried to edit it.

**Comment by lambdalisue** [comment]
Which version of Vim, Git, Gina, and OS do you use? The feature you mentioned are working well in my environment (Neovim v0.4.3, Git 2.23.0, Gina 666852d, macOS) at least.

**Comment by K1DV5** [comment]
git version 2.23.0.windows.1
neovim 0.4.3
Windows 10 1903

I guess windows support needs some time, let me try, where are the mappings handled?

**Comment by lambdalisue** [comment]
It's bit complicated.

- mappings are defined https://github.com/lambdalisue/gina.vim/blob/master/ftplugin/gina-status.vim through actions
- 'index' actions are defined https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/action/index.vim
- when command has executed (like `:Gina add <something>`), an internal `modified:delay` event is emitted
- when `modified:delay` emits `modified` event, `s:on_modified` will be triggered and `:edit` will be trigged on all modified gina buffers like https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/core/emitter.vim#L27-L44

While everything works with Neovim on macOS, I'm guessing there is some timing issue or whatever on Windows. Not just like mapping problems.

**Comment by lambdalisue** [comment]
Ah, not sure but #229 may cause this issue.

**Comment by rzeigler** [comment]
If it is relevant. I have #229 but this issue only occurs in nvim-qt. When I execute from the terminal it works fine.

**Comment by K1DV5** [comment]
I can confirm that it does work in the terminal. I always use nvim-qt so I didn't check it earlier.

**Comment by lambdalisue** [comment]
So the issue may be reproducable with

git version 2.23.0.windows.1
neovim 0.4.3
Windows 10 1903
nvim-qt (Which version?)

right?

**Comment by K1DV5** [comment]
nvim-qt 0.2.14

I should point out that the `<<` map issue is still there in nvim terminal. The `--` map works.

**Comment by rzeigler** [comment]
Sorry, I think my above was unclear. I cannot commit (related error about false not being an editor). For me << works in terminal on windows.

**Comment by lambdalisue** [comment]
@K1DV5 So only `<<` does not work in nvim-qt right? Then prob. https://github.com/equalsraf/neovim-qt/issues/134

**Comment by K1DV5** [comment]
You're right, but since `--` works now, it doesn't matter, can be considered fixed.
