### ISSUE TITLE
Gina status not working

### ISSUE THREAD

**Issue by kerwinxu** [lambdalisue/gina.vim#238]
win10
git: 2.24.1 (msys2)
vim : 8.2 
when i call :Gina status , it open new window to show the result of git status , not show in Quickfix window.

On branch master
Your branch is up to date with 'nickname/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	[31mmodified:   vimrc[m

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	[31m.netrwhist[m
	[31m.vimrc.un~[m
	[31ma[m
	[31mautoload/[m
	[31mcolors/[m
	[31mpugged/[m
	[31mpython3.exe.stackdump[m
	[31mtags.lock[m
	[31mvimrc.bak[m

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by lambdalisue** [comment]
> it open new window to show the result of git status , not show in Quickfix window.

It what `:Gina status` does. Gina does not open Quickfix window.
