### ISSUE TITLE
Problem copying string from Gina log

### ISSUE THREAD

**Issue by weiguoquan422** [lambdalisue/gina.vim#239]
What I want to copy is something like
47c9675 add Measure_Term，Measure_Mode; 16 hours ago <weiguoquan422> (HEAD -> master)  

But when I copy and paste in V mode or ctrl-V mode, the result is
[32m47c9675[m add Measure_Term，Measure_Mode; [33;1m16 hours ago[m [35;1m<weiguoquan422>[m[36;1m (HEAD -> master)[m

How can I solve this problem?

**Comment by lambdalisue** [comment]
Unfortunately, it's a feature for now. Gina relies on the ANSI escape sequence to distinguish terms so it cannot be removed from the buffer content.

PR is welcome 👍

**Comment by lambdalisue** [comment]
You may love https://github.com/chikatoike/concealedyank.vim which remove concealed text when yank.

**Comment by weiguoquan422** [comment]
> You may love https://github.com/chikatoike/concealedyank.vim which remove concealed text when yank.

**Comment by weiguoquan422** [comment]
Thanks, I'll try.
