### ISSUE TITLE
RFC: Auto detection of encoding/format for gina:// buffers

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/gina.vim#24]
Any buffer opened by gina.vim cannot detect the content encoding/format automatically.
Users have to set these options manually if the these are different from the default (open with `:Gina xxx ++enc=xxx ++ff=xxx` or re-read content with `:e ++enc=xxx ++ff=xxx`).

This limitation is due to the performance issue. If I use `Vim.Buffer.edit_content()` internally, the encoding/format can be automatically detected by Vim but the feature is a bit slow.
Personally, I use `utf-8` and most of project I interested also use `utf-8` so current implementation is OK for me.
So I'd like to ask that who want auto-detection and what the priority of the feature for them?

If the priority of the auto-detectin feature is high, I'll probably implement that somehow.

**Comment by bimlas** [comment]
For me it isn't a must-have feature, since I using UTF-8 too (which is a defacto standard in programming I guess).

**Comment by lambdalisue** [comment]
Too old
