### ISSUE TITLE
<< not works in Gina status

### ISSUE THREAD

**Issue by Shatur** [lambdalisue/gina.vim#256]
**Steps to reproduce**
1. Open any repo, make some changes
2. `:Gina status`
3. Navigate to index
4. `<<`

**Actual behavior:**
![изображение](https://user-images.githubusercontent.com/22453358/76703042-0ec4c600-66d7-11ea-93bd-786949920866.png)

**Expected behavior:**
Index staged.

Tested on neovim 0.4.3 without any plugins and configuration config.
`--` shortcut works.

**Comment by lambdalisue** [comment]
Maybe https://github.com/lambdalisue/gina.vim/issues/234#issuecomment-583806607

**Comment by Shatur** [comment]
Yes, the problem exists only in neovim-qt. So the problem is not in the plugin?

**Comment by lambdalisue** [comment]
Yes. (Re)Report this issue on neovim-qt.
