### ISSUE TITLE
Saving the index in Gina patch fails with "does not exist in index"

### ISSUE THREAD

**Issue by ptn** [lambdalisue/gina.vim#259]
After a couple of `dor`s and `dol`s, I do `:w` from the middle buffer, and see this message:

<img width="1440" alt="Screen Shot 2020-04-03 at 3 23 18 AM" src="https://user-images.githubusercontent.com/98363/78334947-b7d64200-755a-11ea-9222-223bd559eb03.png">

What's the correct way to complete the patch operation?

**Comment by lambdalisue** [comment]
> What's the correct way to complete the patch operation?

What you did seems correct but I'm not sure while I have no idea what you did in detail.

Could you give me **a minimum vimrc** and **a step by step procedure** to reproduce the error on my computer?

**a minimum vimrc** is something like https://github.com/lambdalisue/fern.vim/issues/83#issuecomment-586678722

**Comment by ptn** [comment]
I thought this would be a quick question kind of issue, apologies for the incomplete report! Here you go:

Commands I ran in the terminal:

```
dotfiles - master $ cat ~/.vimrc.min
" How to use this vimrc.min
" vim -u ~/vimrc.min
" nvim -u ~/vimrc.min
if has('vim_starting')
  set nocompatible
endif

" Rewrite it to path/to/your/fern.vim
set runtimepath+=~/code/gina.vim

filetype plugin indent on
syntax on


dotfiles - master $ pwd
/Users/ptorres/code/dotfiles


dotfiles - master $ git status -s -b
## master...origin/master [ahead 4]
 M gitconfig


dotfiles - master $ nvim -u ~/.vimrc.min
```

Inside nvim:
1. `:e ~/code/dotfiles/gitconfig`
2. `:Gina patch`
3. `]c`
4. `dor`
5. `:w`

I got this:

<img width="1440" alt="Screen Shot 2020-04-03 at 9 13 12 AM" src="https://user-images.githubusercontent.com/98363/78364669-db65b080-758b-11ea-8793-d625e5853475.png">

---

And same result with `vim -u ~/.vimrc.min`.

**Comment by ptn** [comment]
@lambdalisue just noticed something: the `git apply` command reports it wants to apply `/var/folders/.../2`, but the error message says that `/var/folders/.../1` does not exist. Those numbers are different, and I get that off-by-one difference every single time here. 

From the code, those filenames should really be the same, correct?

```
function! s:apply(git, content) abort
  let tempfile = tempname()
  try
    if writefile(a:content, tempfile) == -1
      return
    endif
    let result = gina#process#call_or_fail(a:git, [
          \ 'apply',
          \ '--verbose',
          \ '--cached',
          \ '--',
          \ tempfile,
          \])
    call gina#core#emitter#emit('command:called:patch')
    return result
  finally
    silent! call delete(tempfile)
  endtry
endfunction
```

I commented out that `finally` and saw that it is the file with the greater number that exists.

I tried setting $TMPDIR to /tmp and it didn't help; I still saw the same off-by-one difference though.

**Comment by ptn** [comment]
Nailed it! In autoload/gina/command/patch.vim, s:patch and s:apply each invoke `tempname`, which means:

1. `s:patch` calculates the diff (correctly) against the filename it received
2. `s:apply` later tries to write that diff to a *different* file, given it again invokes `tempname`

I added log statements and saw this:

![Screen Shot 2020-04-06 at 6 41 32 PM](https://user-images.githubusercontent.com/98363/78612115-931deb00-7836-11ea-81a9-0d1334606b8a.png)

So s:apply should be receiving the filename from s:patch, and write to that.

**Comment by ptn** [comment]
Nailed it. `s:replace_filenames_in_diff` is not replacing anything. This screenshot shows the first line of the diff before and after running all those `substitute`s in that function:

<img width="1280" alt="Screen Shot 2020-04-06 at 20 21 29" src="https://user-images.githubusercontent.com/98363/78617142-67a1fd00-7844-11ea-8488-6e501b23a0d6.png">

I'll see if I can fix it, but I wanted to document the root cause.

**Comment by ptn** [comment]
The problem was that I had this in my git config: diff.noprefix = true. That setting confuses even git itself: you can't do `git diff > patch` and then `git apply patch` with that on (you need to use `git apply -p0 patch`). It's a popular issue, it seems.

No issues without that setting in git. I think this can be closed then.

**Comment by lambdalisue** [comment]
I see. Thanks for the information 👍
