### ISSUE TITLE
Yanking from Gina log is hard

### ISSUE THREAD

**Issue by tssm** [lambdalisue/gina.vim#262]
I know I can press `a` and then use `yank:rev` to copy a commit hash when on this buffer, but in my brain `yw` and others are already burned. If I try to copy a has using normal commands I get `32mxxxxxxxx`, where `xxxxxxxx` is the hash and `32m` is added by Gina, which I guess is an ANSI code. Other ANSI codes are added if I yank other parts of the buffer (like the author name)

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/gina.vim/issues/239 helps?

**Comment by tssm** [comment]
I see, thanks!
