### ISSUE TITLE
Gina always opens splits vertically (one bellow another)

### ISSUE THREAD

**Issue by avucic** [lambdalisue/gina.vim#270]
When I try chaperon for example, whatever option I choose from tab competition it always opens splits one bellow another. I would like to open side by side and solve conflicts.

Also I tried as well `chaperon:vsplit` 

Did I miss something? 
Thanks

**Comment by lambdalisue** [comment]
Maybe the following helps?

```
set diffopt+=vertical
```

Gina respects `diffopt` to find the direction.

**Comment by avucic** [comment]
Thank you soo much !!!
