### ISSUE TITLE
Error with interactive git rebase

### ISSUE THREAD

**Issue by SanchayanMaity** [lambdalisue/gina.vim#276]
Currently, trying interactive rebase with something like `Gina!! rebase -i HEAD~2` results in the below error.

```
hint: Waiting for your editor to close the file... error: There was a problem with the editor 'false'.

[Process exited 1]
```
I had a look at the doc and previous issues #54 and #55. Is interactive rebase supported from within vim? FWIW, I am on neovim nightly.

**Comment by lambdalisue** [comment]
I'm sorry for inconvinience. Well, currently the feature does not work while Gina overwrites `$EDITOR`.
Actually, it's quite difficult to fully support interactive mode through Gina.

It's quite experimental but I'm using https://github.com/lambdalisue/edita.vim on `:terminal` buffer to execute `git rebase -i` in Vim instead.

**Comment by SanchayanMaity** [comment]
Understood. Using `edita` solves my problem and it seems to work with `vim-floaterm` as well without problems. Wasn't aware of it and had not wanted to use `neovim-remote` being a python dependency. This solution is perfectly acceptable.

Thanks a million for your work on gina :), much appreciated. It is so fast even on big repos.

Will consider this issue closed.
