### ISSUE TITLE
Gina patch doesn't respect opener options?

### ISSUE THREAD

**Issue by SanchayanMaity** [lambdalisue/gina.vim#277]
I currently have this setting

```
call gina#custom#command#option(
  \ 'patch', '--oneside',
  \ '--opener', 'botright split'
  \)
```
Yet, calling `:Gina patch` opens a new tab and doesn't respect either the `oneside` or the `--opener` option.

Am I doing something wrong? I have `diffopt+=vertical` as well. Ideally I would like `INDEX` and `WORKTREE` or `HEAD` as well to open in 3 way vertical splits at the bottom.

**Comment by lambdalisue** [comment]
Prob. you need to use the following

```vim
call gina#custom#command#option('patch', '--oneside')
call gina#custom#command#option('patch', '--opener', 'botright split')
```

**Comment by SanchayanMaity** [comment]
Thank you very much. This solves my issue. Closing the issue.
