### ISSUE TITLE
Global mappings are defined after patch action

### ISSUE THREAD

**Issue by obcat** [lambdalisue/gina.vim#284]
**Problem**
After performing the `patch` action, the following mappings are defined globally:

```
n  dor           <Plug>(gina-diffget-r)
	Last set from ~/dotfiles/home/.vim/plugged/gina.vim/autoload/gina/command/patch.vim line 188
n  dol           <Plug>(gina-diffget-l)
	Last set from ~/dotfiles/home/.vim/plugged/gina.vim/autoload/gina/command/patch.vim line 186
n  do            <Plug>(gina-diffget)
	Last set from ~/dotfiles/home/.vim/plugged/gina.vim/autoload/gina/command/patch.vim line 162
n  dp            <Plug>(gina-diffput)
	Last set from ~/dotfiles/home/.vim/plugged/gina.vim/autoload/gina/command/patch.vim line 184
```

**Expected behavior**
I suppose these mappings should be defined as buffer-local mappings for the patch buffers.

**Environment**
- Gina https://github.com/lambdalisue/gina.vim/commit/97116f338f304802ce2661c2e7c0593e691736f8
- Vim 8.2.2300

**Comment by aonemd** [comment]
Hello @lambdalisue if this is not yet resolved, I'd love to take it and send a pull request.

**Comment by lambdalisue** [comment]
@aonemd Thanks. AFAIK, no one takes this. So go for it 👍

**Comment by aonemd** [comment]
Thank you, @lambdalisue! I opened a pull request.
