### ISSUE TITLE
[commit] :wq prompts after vim 8.2.2900

### ISSUE THREAD

**Issue by itchyny** [lambdalisue/gina.vim#290]
Using `:wq` on gina-buffer-commit feature, gina is expected not to show confirmation prompt.
```
Do you want to commit changes? (Y[es]/n[o]):
```
However, starting from [vim 8.2.2900](https://github.com/vim/vim/commit/1174b018a6d705ddb8c04f3d21f78ae760aa0856), which fixes the issue https://github.com/vim/vim/issues/8279, the plugin starts to show confirmation prompt.
It seems that the commit in Vim breaks the assumption of gina at https://github.com/lambdalisue/gina.vim/blob/97116f338f304802ce2661c2e7c0593e691736f8/autoload/gina/command/tag/edit.vim#L111.

**Comment by lambdalisue** [comment]
I see... Do you know any workaround for this?

**Comment by itchyny** [comment]
Removing the following line may fix the issue but not sure it breaks other behaviors. https://github.com/lambdalisue/gina.vim/blob/7069668147157d872821ebed1eee07742ece48fd/autoload/gina/command/commit.vim#L318

**Comment by lambdalisue** [comment]
Hum... That would break the behavior of `:q` which should show the prompt otherwise unwilling commit will be performed.

**Comment by itchyny** [comment]
How about checking the last command then?
```vim
  if histget('cmd', -1) !~# '^\(wq\|x\%[it]\|exi\%[t]\)'
    silent! unlet b:gina_BufWriteCmd
  endif
```
This is not perfect and does not work with `ZZ` though (should not prompt). But note that `ZQ` is unchecked (in [L309](https://github.com/lambdalisue/gina.vim/blob/7069668147157d872821ebed1eee07742ece48fd/autoload/gina/command/commit.vim#L309)) and invokes the commit unlike `:q!`.

**Comment by lambdalisue** [comment]
Nice. Would you mind if I ask you to create a PR for that?
