### ISSUE TITLE
Lsp Servers Cannot find root dir on file-like gina buffers

### ISSUE THREAD

**Issue by thecontinium** [lambdalisue/gina.vim#294]
Hi

I am using gina to compare git differences along with LSP servers and [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) 

Gina assigns names in the format [gina://...](https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L679) with a buftype of[ nowrite](https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L657) to the git version of the file.

Lspconfig attempts to find the root project directory for these types of buffers.
It tries all buffers except those that are  of buftype[ nofile](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L205) resulting in many notifications on the git version of the buffer that the root dir cannot be found.

I am not sure where this should be fixed but would welcome your thoughts on the best solution ?

Cheers

**Comment by lambdalisue** [comment]
That's nvim-lspconfig issue while gina buffer is not file buffer and that is determinable from it's buffer name.

**Comment by thecontinium** [comment]
As your classification highlights it is a file. So it warrants coverage by Lsp but with the root directory of the respective file on disk rather than attempting to find the root of a file from git. Thanks for your input I will close this.
