### ISSUE TITLE
How to get back from :Gina status ?

### ISSUE THREAD

**Issue by abitrolly** [lambdalisue/gina.vim#297]
When I run `:Gina status` my current file is replaced with its output. When I `:q` the window, `vim` exits completely. How to return to the file I was editing?

Installed `gina.vim` like this.
```
git clone --depth 1 https://github.com/lambdalisue/gina.vim ~/.vim/pack/plugins/start/gina.vim
```

**Comment by lambdalisue** [comment]
See `:help jump-motions`. That's Vim's native feature so please move onto StackOverflow or similar if you have more questions about this topic.
