### ISSUE TITLE
How to update `gina#component#traffic#preset()` in the background

### ISSUE THREAD

**Issue by GordianDziwis** [lambdalisue/gina.vim#301]
The traffic statusline component only gets updated when doing a `!gina status` or `:!git status`. Is it possible to keep it updated automatically in the background?

**Comment by lambdalisue** [comment]
It should be updated automatically. Do you use `git` command in terminal or so on?

**Comment by GordianDziwis** [comment]
When I run `git status` in an external terminal it gets updated.

But also only after I run some kind of status command. I tried it with a minimal vimrc;

```vim
set nocompatible
filetype off

call plug#begin('~/.neovim/bundle')
Plug 'lambdalisue/gina.vim'
call plug#end()

syntax on
```

NVIM v0.7.0-dev and gina is abdbe0fe33f3b6fc59e94f7cc3072768f8dfd8ac

**Comment by lambdalisue** [comment]
Thanks for a minimal vimrc but it seems the vimrc does not have `gina#component#traffic#preset()`. How can I reproduce your situation?

**Comment by GordianDziwis** [comment]
1. Checkout a github repo
2. Open file in repo with vim
3. In vim `:echo gina#component#traffic#preset()` # Empty
4. Create a commit with the github GUI
5. In vim `:echo gina#component#traffic#preset()` # Empty, but should show that local branch is one commit behind,
6. Do a `git status`
7. In vim `:echo gina#component#traffic#preset()` # Now it shows that the local branch is behind

**Comment by lambdalisue** [comment]
Finally, I got your situation. I'm sorry but it's feature. Gina watch the last modified data of `.git/index` thus cannot detect changes on remote until `git` itself update `.git/index` or so on.

**Comment by GordianDziwis** [comment]
Thanks, then I'll use an autocommand.
