### ISSUE TITLE
Change the command syntax for {revision} and/or {path}

### ISSUE THREAD

**Issue by bimlas** [lambdalisue/gina.vim#36]
I think there are some inconsistent behavior in the plugin from the view of a (command line) Git user.

For example `Gina info` invokes `git show`, while `Gina show` is some kind of buffer-related-git-show. I think it would be consistent to swap the command names.

Another thing what I don't understand: why it has to [clean the commit message](https://github.com/lambdalisue/gina.vim/blob/256a3c7a56c9d541f185cfa9ff6e3a26aefcce84/test/gina/command/commit.vimspec#L94) manually (07c177f)? Why don't you leave it to Git to do what already knows? Actually it trims the blank lines at the top of the buffer for me (on Windows, using commit message template via Git `commit.template`config) plus when a new `commit.cleanup` option will be added to Git, you have to write the same function for Gina.

**Comment by lambdalisue** [comment]
> For example Gina info invokes git show, while Gina show is some kind of buffer-related-git-show. I think it would be consistent to swap the command names.

Do you have any alternative idea?

> Another thing what I don't understand: why it has to clean the commit message manually (07c177f)? Why don't you leave it to Git to do what already knows? Actually it trims the blank lines at the top of the buffer for me (on Windows, using commit message template via Git commit.templateconfig) plus when a new commit.cleanup option will be added to Git, you have to write the same function for Gina.

Yes. It would be nice if git did that thing for us... git does NOT strip commentary when a commit message has passed by `-F{filename}` option which internally gina rely on. That's why gina need to strip commentary before making a template file for `-F`.

> Actually it trims the blank lines at the top of the buffer for me (on Windows, using commit message template

It sounds a bug. Please make a new issue as a bug report (and if you can, please write a test)

**Comment by lambdalisue** [comment]
Wait. What's happen if I specify `--cleanup` option with `-F`. I don't remember if I tried that. I'll consider that

**Comment by bimlas** [comment]
It seems to work for me: `git commit --cleanup strip -F message`

**Comment by lambdalisue** [comment]
Thanks! Then I'll fix the commit message issue with that.

**Comment by bimlas** [comment]
Please verify by yourself too first (remember: I have a special environment)!

**Comment by lambdalisue** [comment]
Yes of course :+1: Actually `Gina commit` is a bit complicated so I still not sure if `--strip` can be used but it's worth to try.

**Comment by lambdalisue** [comment]
As I commented #37, unfortunately the approach does not work for `--cleanup=scissors` or so on and could not be used.

**Comment by lambdalisue** [comment]
So please create a new issue to describe the detail (how to reproduce or so on)

> Actually it trims the blank lines at the top of the buffer for me (on Windows, using commit message template

While it seems a bug (and if you can, could you write tests for that in `test/gina/command/commit.vimspec`?)

**Comment by lambdalisue** [comment]
And for this issue.

> For example Gina info invokes git show, while Gina show is some kind of buffer-related-git-show. I think it would be consistent to swap the command names.

Any alternative ideas?

**Comment by bimlas** [comment]
Well... Before giving a new name for it: actually what's the difference between `Gina show` and `Gina info`? If only that `show` adds the path of the file to the end of SHA (so `Gina show` on README.md is equivalent to `Gina info -- README.md`) then I think `Gina info` should be deleted, because it's a duplication of the same functionality.

**EDIT**

Sorry: `show` should be deleted... You know what I mean I hope.

**Comment by lambdalisue** [comment]
Completely different

- `:Gina show HEAD -- README.md` execute `git show HEAD:README.md` and show a **content** of README.md at HEAD
- `:Gina info HEAD -- README.md` execute `git show HEAD -- README.md` and show a **commit** of HEAD filtered with README.md (so mostly nothing will be shown while I haven't edit README.md)

Is these behavior different in your enviornment? Then it would be a bug.

**Comment by bimlas** [comment]
OK, I think I understand: what confused me is that on command line I use `git show` to show contents of file and commits too, but I know that this is hard to reproduce in a Vim script. 

Getting back to the issue: `Gina show` -> `Gina show-file`?

PS.: Sorry for disturbing you but Git users likes to use the plugin as on command line (maybe), this is why I forcing these things.

**Comment by bimlas** [comment]
I cannot stop my mind, sorry.

Here's an example: I want to find the changes of `qrep` in Gina.

On command line:
```
# Find the relevant commits.
$ git log --all -G qrep
# View the commit I'm interested in ('-G' to view only relevant files in commit).
$ git show b8f654d -G qrep
# View the content of file in the commit.
$ git show b8f654d:autoload/gina/command/qrep.vim
```

Gina way:
```
# Find the relevant commits.
:Gina log --all -G qrep
# View the commit I'm interested in ('-G' to view only relevant files in commit).
<CR> on entry or 'Gina info b8f654d -G qrep -- /' to view only relevant files
# View the content of file in the commit.
$ git show b8f654d -- autoload/gina/command/qrep.vim
```

From the view of a command line Git user Gina seems to be inconsistent because it using two commands (`info`, `show`) to behave like `git show`. This is why I started this issue.

While I wrote these lines I just realized the big difference between command line and Gina: `Gina show` and `Gina info` adds the path of currently opened file to the end of the SHA while you have to do by hand on command line.

I think I liked to have a full Vim replacement of command line Git, where I can do exactly the same. Maybe I have to rethink my Git workflow, but I will write use cases where command line is more useful than Git to give you ideas (if you don't mind).

**Comment by lambdalisue** [comment]
Gina way:
```
# Find the relevant commits.
:Gina log --all -G qrep
# View the commit I'm interested in ('-G' to view only relevant files in commit).
<CR> on entry or 'Gina info b8f654d -G qrep -- /' to view only relevant files
# View the content of file in the commit. (execute the following on `gina://xxxxx:info/b8f654d`)
:Gina show -- autoload/gina/command/qrep.vim
```

Anyway, so

1. Is this just a name problem? Renaming like `Gina info -> Gina show` and `Gina show -> Gina show-file` (or else) solves?
2. Do you mean you would like to do `:Gina show b8f654d:autoload/gina/command/qrep.vim`? In this case, gina would lost the ability to guess which revision or which file should `:Gina show` open from a current buffer name (e.g. `Gina show` on `gina://xxxxx:diff/HEAD~:autoload/gina/command/qrep.vim` opens `gina://xxxxx:show/HEAD~:autoload/gina/command/qrep.vim` so users do not have to call `:Gina show HEAD~ -- autoload/gina/command/qrep.vim`)

**Comment by lambdalisue** [comment]
OK. I think I should re-consider all command syntaxes.

**Comment by bimlas** [comment]
Why did you change your mind? :frowning:

**Comment by lambdalisue** [comment]
Wait a minutes.

**Comment by lambdalisue** [comment]
## `-- {pathspec}`

This is for **filtering** as usual CUI program does.
The filteration will be performed by `git` so gina simply ignore the argument.

This is used for commands which shows a non file-like buffer.
The following commands would support this (only when a git raw command supports)

- `:Gina branch`
- `:Gina changes`
- `:Gina commit`
- `:Gina grep`
- `:Gina log`
- `:Gina ls`
- `:Gina qrep`
- `:Gina reflog`
- `:Gina status`
- `:Gina tag`

Additionally, this is used to filter the result for the repository-wide command.
The following commands would support

- `:Gina diff`
- `:Gina show`

For example
```
:Gina ls -- **/*.vim
-- Opens gina://xxxxx:ls
-- List filenames in index which matches with **/*.vim

:Gina show -- **/*.vim
-- Opens gina://xxxxx:show
-- Show a commit of the repository which matches with **/*.vim

:Gina diff HEAD -- README.md
-- Opens gina://xxxxx:diff/HEAD
-- Show a diff of the repository which matches with README.md
-- This is not conceptulally eqaul to a diff of README.md
```

## `{object}`

This is for **specifing** as like `git show` does.

This is used for commands which requires `{revision}` and shows a file-like buffer.
The following commands support this

- `:Gina browse`
- `:Gina compare`
- `:Gina diff`
- `:Gina show`

The format of `{object}` is `{revision}[:{path}]`. For example

- `{revision}:{path}` is used to specify revision and path
- `{revision}:` is used to specify revision and the path is guessed from the current buffer
- `:{path}` is used to specify path and the revision is guessed from the current buffer
- `:0:{path}` is used to specify path and omit the revision (INDEX)
- `:0:` is used to guess path and omit the revision (INDEX)
- `:` is used to guess path and the revision
- `{revision}` is used to specify revision and omit the path
- `:0` is used to omit the path and revision
- An empty string is used to guess revision and omit the path

For example
```
Assume the followings are performed on gina://xxxxx:diff/develop:README.md

:Gina show HEAD:LICENSE
-- Opens gina://xxxxx:show/HEAD:LICENSE
-- A content of LICENSE in HEAD

:Gina show HEAD:
-- Opens gina://xxxxx:show/HEAD:README.md
-- A content of README.md in HEAD
-- A {path} was guessed

:Gina show :LICENSE
-- Opens gina://xxxxx:show/develop:LICENSE
-- A content of LICENSE in develop
-- A {revision} was guessed

:Gina show :0:LICENSE
-- Opens gina://xxxxx:show/:LICENSE
-- A content of LICENSE in INDEX
-- A {revision} was omitted

:Gina show :0:
-- Opens gina://xxxxx:show/:README.md
-- A content of README.md in INDEX
-- A {path} was guessed
-- A {revision} was omitted

:Gina show :
-- Opens gina://xxxxx:show/develop:README.md
-- A content of README.md in develop
-- A {path} was guessed
-- A {revision} was guessed

:Gina show HEAD
-- Opens gina://xxxxx:show/HEAD
-- A commit of HEAD
-- A {path} was omitted
-- A {revision} was guessed

:Gina show :0
-- Opens gina://xxxxx:show
-- A commit of INDEX
-- A {path} was omitted
-- A {revision} was omitted

:Gina show
-- Opens gina://xxxxx:show/develop
-- A commit of develop
-- A {path} was omitted
-- A {revision} was guessed
```

## `{path}`
This is used for commands which requires `{path}` but `{revision}` and shows a file-like bufer.
The following commands support this

- `:Gina chaperon`
- `:Gina edit`
- `:Gina log`
- `:Gina patch`

For example
```
:Gina chaperon README.md
-- Opens gina://xxxxx:show/:2:README.md, README.md, and gina://xxxxx:show/:3:README.md

:Gina log README.md
-- Opens gina://xxxxx:log/:README.md
-- <Return> on this buffer opens gina://xxxxx:show/XXXXX:README.md

:Gina edit (on gina://xxxxx:show/HEAD:README.md)
-- Opens README.md
-- Thea file name has guessed from the previous buffer name
```

**Comment by lambdalisue** [comment]
Let me know if the rule above have some missing points or confliction

**Comment by lambdalisue** [comment]
Ah... wait. I'll change

**Comment by bimlas** [comment]
It seems to be compatible with raw Git, sounds good. :clap: 

Some notes:
* `Gina branch`, `commit`, `tag` don't need `-- <path>`
* Let Git handle the `<sha>`, `<sha>:<path>` and `-- <path>`: shouldn't need to parse or do anything on it (I'm not sure in this one)
* Acutally only `git show` produce file content (I think) when `<sha>:<path>` format is used; otherwise it shows diff/commit

So only `git show` needs some preapration to determine the output: is it file content or not.

I think (to be compatible with the current Gina behaviour) invoking a Gina command without `<path>` or `<sha>` should set up `<path>` to the actual buffer.

Here's a list of Git commands.

### Only non file-like content can be displayed (diff, commit or just echoing)

**Gina commit ~= git commit**
```
git commit [-a | --interactive | --patch] [-s] [-v] [-u<mode>] [--amend]
	   [--dry-run] [(-c | -C | --fixup | --squash) <commit>]
	   [-F <file> | -m <msg>] [--reset-author] [--allow-empty]
	   [--allow-empty-message] [--no-verify] [-e] [--author=<author>]
	   [--date=<date>] [--cleanup=<mode>] [--[no-]status]
	   [-i | -o] [-S[<keyid>]] [--] [<file>…​]
```

**Gina grep ~= git grep**
**Gina qrep ~= git grep**
```
git grep [-a | --text] [-I] [--textconv] [-i | --ignore-case] [-w | --word-regexp]
	   [-v | --invert-match] [-h|-H] [--full-name]
	   [-E | --extended-regexp] [-G | --basic-regexp]
	   [-P | --perl-regexp]
	   [-F | --fixed-strings] [-n | --line-number]
	   [-l | --files-with-matches] [-L | --files-without-match]
	   [(-O | --open-files-in-pager) [<pager>]]
	   [-z | --null]
	   [-c | --count] [--all-match] [-q | --quiet]
	   [--max-depth <depth>]
	   [--color[=<when>] | --no-color]
	   [--break] [--heading] [-p | --show-function]
	   [-A <post-context>] [-B <pre-context>] [-C <context>]
	   [-W | --function-context]
	   [--threads <num>]
	   [-f <file>] [-e] <pattern>
	   [--and|--or|--not|(|)|-e <pattern>…​]
	   [ [--[no-]exclude-standard] [--cached | --no-index | --untracked] | <tree>…​]
	   [--] [<pathspec>…​]
```

**Gina ls ~= git ls-files**
```
git ls-files [-z] [-t] [-v]
		(--[cached|deleted|others|ignored|stage|unmerged|killed|modified])*
		(-[c|d|o|i|s|u|k|m])*
		[--eol]
		[-x <pattern>|--exclude=<pattern>]
		[-X <file>|--exclude-from=<file>]
		[--exclude-per-directory=<file>]
		[--exclude-standard]
		[--error-unmatch] [--with-tree=<tree-ish>]
		[--full-name] [--recurse-submodules]
		[--abbrev] [--] [<file>…​]
```

**Gina reflog ~= git reflog**
```
git reflog [show] [log-options] [<ref>]
git reflog expire [--expire=<time>] [--expire-unreachable=<time>]
	[--rewrite] [--updateref] [--stale-fix]
	[--dry-run] [--verbose] [--all | <refs>…​]
git reflog delete [--rewrite] [--updateref]
	[--dry-run] [--verbose] ref@{specifier}…​
git reflog exists <ref>
```

**Gina status ~= git status**
```
git status [<options>…​] [--] [<pathspec>…​]
```

**Gina tag ~= git tag** (cannot use with `-- <path>`)
```
git tag [-a | -s | -u <keyid>] [-f] [-m <msg> | -F <file>]
	<tagname> [<commit> | <object>]
git tag -d <tagname>…​
git tag [-n[<num>]] -l [--contains <commit>] [--points-at <object>]
	[--column[=<options>] | --no-column] [--create-reflog] [--sort=<key>]
	[--format=<format>] [--[no-]merged [<commit>]] [<pattern>…​]
git tag -v <tagname>…​
```

**Gina changes ~= git diff --name-status**
**Gina diff ~= git diff**
```
git diff [options] [<commit>] [--] [<path>…​]
git diff [options] --cached [<commit>] [--] [<path>…​]
git diff [options] <commit> <commit> [--] [<path>…​]
git diff [options] <blob> <blob>
git diff [options] [--no-index] [--] <path> <path>
```

**Gina log ~= git log**
```
git log [<options>] [<revision range>] [[\--] <path>…​]
```

**Gina branch ~= git branch** (cannot use with `-- <path>`)
```
git branch [--color[=<when>] | --no-color] [-r | -a]
	[--list] [-v [--abbrev=<length> | --no-abbrev]]
	[--column[=<options>] | --no-column]
	[(--merged | --no-merged | --contains) [<commit>]] [--sort=<key>]
	[--points-at <object>] [<pattern>…​]
git branch [--set-upstream | --track | --no-track] [-l] [-f] <branchname> [<start-point>]
git branch (--set-upstream-to=<upstream> | -u <upstream>) [<branchname>]
git branch --unset-upstream [<branchname>]
git branch (-m | -M) [<oldbranch>] <newbranch>
git branch (-d | -D) [-r] <branchname>…​
git branch --edit-description [<branchname>]
```

### Can display file content and commit too

It displays non file-like content with `-- <path>` and file content with `<sha>:path`.

**Gina show ~= git show**
```
git show [options] <object>…​
```

### Cannot identify

* Gina browse ~= ???
* Gina compare ~= git show ???
* Gina chaperon ~= ???
* Gina edit ~= ???
* Gina patch ~= git show ???

**Comment by lambdalisue** [comment]
See #40

**Comment by lambdalisue** [comment]
The #40 still fail and actions won't work yet

**Comment by bimlas** [comment]
One more note to #40: `Gina show {rev} -- {path}` should show commit (if possible) to be compatible with CUI.

**Comment by bimlas** [comment]
Anyway: a big thanks for considering my thoughts! I'm absolutely amazed by your skills! :heart_eyes:

**Comment by lambdalisue** [comment]
See the table. info is now show and Gina show rev -- path is already there :+1:
