### ISSUE TITLE
Let git to remove commentary

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/gina.vim#37]
https://github.com/lambdalisue/gina.vim/issues/36#issuecomment-281600690

**Comment by lambdalisue** [comment]
Unfortunately, it cannot be used

>        --cleanup=<mode>
>            This option determines how the supplied commit message should be cleaned up before committing. The <mode> can be strip,
>            whitespace, verbatim, scissors or default.
> 
>            strip
>                Strip leading and trailing empty lines, trailing whitespace, commentary and collapse consecutive empty lines.
> 
>            whitespace
>                Same as strip except #commentary is not removed.
> 
>            verbatim
>                Do not change the message at all.
> 
>            scissors
>                Same as whitespace, except that everything from (and including) the line "# ------------------------ >8
>                ------------------------" is truncated if the message is to be edited. "#" can be customized with core.commentChar.
> 
>            default
>                Same as strip if the message is to be edited. Otherwise whitespace.
> 
>            The default can be changed by the commit.cleanup configuration variable (see git-config(1)).

So only `--cleanup=strip` works for non-editing mode. Other cleanup method requires the message is to be edited.

**Comment by bimlas** [comment]
`scissors` does not remove the comments regardless that the message is edited or not - if someone sets up this mode in .gitconfig, then he/she doesn't want to remove comments I think. So it works as expected.

**Comment by lambdalisue** [comment]
No. Then gina cannot support `git commit --verbose` and that a problem.

**Comment by bimlas** [comment]
Got it: on `--cleanup scissors` the template of commit message differs from the others.

`git commit --verbose --cleanup scissors`: there is a scissor above status, everything excluded from commit message below that (status and results of `--verbose` too)
```diff
Commit message
# This comment will be in commit message.

# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   README.adoc
#
# Untracked files:
#	message
#
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
diff --git a/README.adoc b/README.adoc
index 12b5e40..af9dd6f 100644
--- a/README.adoc
+++ b/README.adoc
@@ -1 +1,2 @@
 = Sandbox repository for testing Git features
+dsd
```

`git commit --verbose --cleanup strip`: Every comment removed + lines below the scissor.
```diff
Commit message
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   README.adoc
#
# Untracked files:
#	message
#
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
diff --git a/README.adoc b/README.adoc
index 12b5e40..af9dd6f 100644
--- a/README.adoc
+++ b/README.adoc
@@ -1 +1,2 @@
 = Sandbox repository for testing Git features
+dsd
```

It seems that Gina reads the rightly formatted commit template, so `--cleanup` should work.

**Comment by lambdalisue** [comment]
Oh, I got. OK I'll do it thanks!

**Comment by lambdalisue** [comment]
It seems the method does not work for `git -c core.editor=false commit -F{filename} --cleanup=strip` which gina.vim use to obtain a correct commit message.

Assume that `message.txt` has

```
asdfasdfasdf
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   autoload/gina/command/commit.vim
#	modified:   test/gina/command/commit.vimspec
#
```

When I perform `git -c core.editor=false commit --edit -Fmessage.txt --cleanup=strip`, the content of `COMMIT_EDITMSG` become

```
Subject

Body.Body.Body
Body.Body.Body
Body.Body.Body

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   autoload/gina/command/commit.vim
#	modified:   test/gina/command/commit.vimspec
#

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   autoload/gina/command/commit.vim
#	modified:   test/gina/command/commit.vimspec
#
# Untracked files:
#	message.txt
#
```

If I perform that without `--no-edit`, a correct commit message would be committed and `COMMIT_EDITMSG` become

```
Subject

Body.Body.Body
Body.Body.Body
Body.Body.Body

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   autoload/gina/command/commit.vim
#	modified:   test/gina/command/commit.vimspec
#
```

So the choice are

1. Forget about this. Stack on a self-cleanup method and focus to improve that feature
2. Perform commit without `--no-edit` and reset commit by `git reset --soft HEAD~` or `git reset --soft HEAD@{1}` to get a correct commit message
3. Use a self-cleanup for reading, let git to do that on commit.

If the second choice won't affect a commit log, I'm ok to do that but I think it would affect somehow...

**Comment by lambdalisue** [comment]
Do you know does `git reset --soft HEAD@{1}` affect something? It seems ok to use.

**Comment by lambdalisue** [comment]
No.... I tried but the result of `git reflog` is really messed up.

```
[33m16b6ed1[m HEAD@{0}: commit: Subject
[33m1a78475[m HEAD@{1}: reset: moving to HEAD@{1}
[33m94bfea9[m HEAD@{2}: commit: Subject
[33m1a78475[m HEAD@{3}: reset: moving to HEAD@{1}
[33m1b3903c[m HEAD@{4}: commit: Subject
[33m1a78475[m HEAD@{5}: reset: moving to HEAD@{1}
[33mf96f23a[m HEAD@{6}: commit: Subject
[33m1a78475[m HEAD@{7}: reset: moving to HEAD@{1}
[33mc7c749e[m HEAD@{8}: commit: Subject
[33m1a78475[m HEAD@{9}: reset: moving to HEAD@{1}
[33mc7c749e[m HEAD@{10}: commit: Subject
[33m1a78475[m HEAD@{11}: reset: moving to HEAD@{1}
[33mf98573e[m HEAD@{12}: commit: Subject
[33m1a78475[m HEAD@{13}: reset: moving to HEAD@{1}
[33me40029a[m HEAD@{14}: commit: Subject
[33m1a78475[m HEAD@{15}: reset: moving to HEAD@{1}
[33m7f8b52d[m HEAD@{16}: commit: Subject
[33m1a78475[m HEAD@{17}: reset: moving to HEAD@{1}
[33maa91e67[m HEAD@{18}: commit: Subject
[33m1a78475[m HEAD@{19}: reset: moving to HEAD@{1}
[33md784341[m HEAD@{20}: commit:
[33m1a78475[m HEAD@{21}: reset: moving to HEAD@{1}
[33md784341[m HEAD@{22}: commit:
[33m1a78475[m HEAD@{23}: reset: moving to HEAD@{1}
[33m4d878f0[m HEAD@{24}: commit:
[33m1a78475[m HEAD@{25}: reset: moving to HEAD@{1}
[33mc311155[m HEAD@{26}: commit:
[33m1a78475[m HEAD@{27}: reset: moving to HEAD@{1}
[33m320893c[m HEAD@{28}: commit:
[33m1a78475[m HEAD@{29}: reset: moving to HEAD@{1}
[33m320893c[m HEAD@{30}: commit:
[33m1a78475[m HEAD@{31}: reset: moving to HEAD@{1}
[33maa06e43[m HEAD@{32}: commit:
[33m1a78475[m HEAD@{33}: reset: moving to HEAD@{1}
[33mcea3339[m HEAD@{34}: commit:
[33m1a78475[m HEAD@{35}: reset: moving to HEAD@{1}
[33mcd5c8cb[m HEAD@{36}: commit:
[33m1a78475[m HEAD@{37}: reset: moving to HEAD@{1}
[33m31f80c3[m HEAD@{38}: commit: Subject
[33m1a78475[m HEAD@{39}: reset: moving to HEAD~
[33m230e5ec[m HEAD@{40}: commit: SUBJECT
[33m1a78475[m HEAD@{41}: commit: Add '_verbose' mode to make 'scissors' correct
[33me467bdd[m HEAD@{42}: commit: keepjumps was required for %delete _
[33mc5f0d7a[m HEAD@{43}: commit: Support +cmd for Command which opens a buffer
[33mf0fce21[m HEAD@{44}: commit: Fix #34: Behavior for jumplist
```

**Comment by lambdalisue** [comment]
I'm trying `git reflog delete HEAD@{0}` now...

**Comment by lambdalisue** [comment]
I succeeded to implement that feature :tada: But there is a following limitation
 
## Limitation

When user sequentially perform the following command, diff part of the commit could not be removed.

1. Open a `gina-commit` buffer with `:Gina commit --verbose`
2. Write some message and save the message to the cache by `:w`
3. Re-open with `:Gina commit`
4. The cached diff part remains and no way to remove that (except the user manually remove)
5. If user commit without any modification, the diff part will be committed as well.

**Comment by lambdalisue** [comment]
Done by https://github.com/lambdalisue/gina.vim/commit/2caa9e4ca16219730acf3735a0bd763b243fa9e8
