### ISSUE TITLE
Add gitgutter like feature with async

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/gina.vim#56]
I like gitgutter but I don't use it while it slow vim on my old Mac. So it would be nice if gina add similar feature with async.

**Comment by SevereOverfl0w** [comment]
gitgutter runs async now. Is this still a desire?

**Comment by lambdalisue** [comment]
Oh, I didn't know that thanks. However

1. gitgutter use a different mech for detecting a git repository and I like the gina's way
2. Detecting git repository cost a bit so it would be nice if gina provide same feature

So I would like. But the priority is low for now:+1:

**Comment by lambdalisue** [comment]
Too old
