### ISSUE TITLE
Gina command that operate on buffer pollutes `<C-^>`

### ISSUE THREAD

**Issue by hauleth** [lambdalisue/gina.vim#58]
Way to reproduce:

+ open any file in Git repo
+ go to other file
+ `:Gina status`
+ `:q`
+ `<C-^>`

And you land in `gina://api:status/` instead of firstly opened file.

**Comment by lambdalisue** [comment]
`:keepalt Gina status` may help?

**Comment by lambdalisue** [comment]
So what do you think about this? @hauleth

**Comment by hauleth** [comment]
Works
