### ISSUE TITLE
Filetype incorrectly set when opening Gina blame :

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#60]
When using with [tscompletejob](https://github.com/runoshun/tscompletejob) `:Gina blame :` doesn't work.

Instead I get the following error:
![image](https://cloud.githubusercontent.com/assets/287744/23563150/44829dae-fffa-11e6-962d-ce9f37fe11c1.png)

I add more logs to `tscompletejob` and found that the filetype of gina is set `typescript` hence tscompletejob throws error:

![image](https://cloud.githubusercontent.com/assets/287744/23959911/b77d4b2a-0963-11e7-9814-0a498e7dd463.png)

I add `echom` log in `tscompletejob/autoload/tscompletejob/bufmanager.vim` to print the filetype

```vim
func! s:addBuffer(filename) dict
    echom a:filename . ' ' . &ft
    let bn = s:getkey(a:filename)
    let filename = tscompletejob#utils#abspath(a:filename)
    if (l:bn == -1)
        throw "invalid buffer"
    elseif (!has_key(self.buffers, string(bn)))
        let self.buffers[string(l:bn)] = {
                    \ "filename" : filename,
                    \ "tmpfile" : tempname(),
                    \ "is_opened" : 0,
                    \ }
    endif
    return bn
endfunc
```

Seems to me more like a bug in `Gina` than in `tscompletejob`.

Note: I'm using vim8 on windows.

**Comment by lambdalisue** [comment]
It seems the bug is on tscompletejob. Gina is using a protocol scheme (`gina://`) so tscompletejob SHOULD ignore such buffer name (for example, `:e http://brabrabra/something.ts` would raise same exception I guess)

**Comment by prabirshrestha** [comment]
@lambdalisue doesn't seems like a tscompletejob bug to me. Other plugins are also breaking. Here is another one https://github.com/justinmk/vim-gtfo. If I try to open the terminal in the current buffer working directory it fails. It even fails after closing the blame window by `:q`. I need to enter `:bd` and then it goes back to the actual file buffer. I don't think it would be good to force all plugin authors to look for the prefix of the file.

![image](https://cloud.githubusercontent.com/assets/287744/24319414/679d77ca-10d8-11e7-8447-82e4d68c18a5.png)

**Comment by lambdalisue** [comment]
No. It is not gina's fault. vim-gtfo **SHOULD** check if the current buffer is for a local file while it depends on a LOCAL file and Vim can open a remote file, files in zip, or whatever.

**Comment by prabirshrestha** [comment]
Is there a better way to check protocol somewhat like '&filetype' of do we need to parse filename manually?

**Comment by lambdalisue** [comment]
Something like

```vim
if bufname('%') =~# '^\w\+://'
    echo 'File is not in a local file system'
else
    echo 'File is in a local file system'
endif
```

**Comment by prabirshrestha** [comment]
this has been fixed in tscomplete plugin. https://github.com/runoshun/tscompletejob/commit/84089726ec13fa0a12f04fc88674997ba0cab306
