### ISSUE TITLE
Show branch and commit count behind or ahead of remote in `Gina status`

### ISSUE THREAD

**Issue by bimlas** [lambdalisue/gina.vim#65]
I think the `branch` and `traffic` need to be in `Gina status` too: there's no other way to find out the traffic (as I know), but the statusline components. If somebody don't want to use the components, then (s)he has to open `Gina branch` (for current branch name) and `Gina log --all` (for traffic) to be informed. These infos are part of the `git status` so it would be nice to set the `Gina status` buffer statusline locally (`setlocal statusline=...`) to show it.

Related to #15

**Comment by lambdalisue** [comment]
I may allow to use non SHORT format for `Gina status`.

**Comment by lambdalisue** [comment]
`--branch` is now allowed from https://github.com/lambdalisue/gina.vim/commit/f4d65a6652ab30bee71da250930cf13bffe9cfd5
