### ISSUE TITLE
E689: Can only index a List or Dictionary

### ISSUE THREAD

**Issue by archseer** [lambdalisue/gina.vim#66]
"gina://my_project:status" [Read errors] --No lines in buffer--
Error detected while processing function <SNR>155_BufReadCmd[9]..gina#process#open[5]..<SNR>112_build_raw_args[9]..gina#core#askpass#wrap[2]..<SNR>131_askpass[1]..gina#core#repo#config[13]..<SNR>122_exten
d_config:
line   12:
E689: Can only index a List or Dictionary

**Comment by archseer** [comment]
(This is on neovim 0.1.7)

**Comment by lambdalisue** [comment]
It seems a bug but in case, could vou write reproduce steps?

**Comment by archseer** [comment]
Happens on any `:Gina` command, I can't use the plugin at all -- was migrating from `vim-gita` which seems to work fine

**Comment by lambdalisue** [comment]
For now, set something to git config may solve the issue.

**Comment by lambdalisue** [comment]
And which os do you use?

**Comment by lambdalisue** [comment]
I checked the code but could not find a problem. could you paste a result of git config --list ?

**Comment by lambdalisue** [comment]
I think I got the reason. Could you try #67 ?

**Comment by lambdalisue** [comment]
Note, in case, I would like to know your git config --list

**Comment by archseer** [comment]
#67 solves it for me! my git config is available here https://github.com/archSeer/dotfiles/blob/master/gitconfig

**Comment by lambdalisue** [comment]
Merged. Thanks 👍
