### ISSUE TITLE
exists('*gina#component#repo#branch') equal to 0

### ISSUE THREAD

**Issue by tracyone** [lambdalisue/gina.vim#68]
hi @lambdalisue 

`exists('*gina#component#repo#branch') ` always return 0. But 

`echo gina#component#repo#branch()` can get the branch name....

after one call of gina#component#repo#branch(), `exists('*gina#component#repo#branch') `  will return 1 

```vim
    if exists('*gina#component#repo#branch')
        return gina#component#repo#branch()
    endif
```

**Comment by wsdjeg** [comment]
@tracyone 
`echo gina#component#repo#branch()` will search rtp, and the script will be loaded,

`exists('*gina#component#repo#branch')` only return 1, when this script is loaded, 

you should not check autoload func like this. you can use `try catch` instead.

**Comment by wsdjeg** [comment]
```vim
let p = ''

  try
    let p = gina#component#repo#branch()
  catch /^Vim\%((\a\+)\)\=:E117/
  endtry

if !empty(p)
   return p
endif
```

**Comment by tracyone** [comment]
thanks
