### ISSUE TITLE
Change every backslash to forwardslash in pathspec on Windows

### ISSUE THREAD

**Issue by bimlas** [lambdalisue/gina.vim#7]
`Gina log -- :/` drops `fatal: :\: '\' is outside repository` error on Windows. Changing the `\` to `/` solves the problem.

Since `Gina log -- path/to/directory` shows the changes of a directory, it can be used to show the history of certain files too, for example `Gina log -- :/ :!/**.vim` will list the commits of non-Vim files (try `git log --name-status -- :/ :!/**.vim` to see the files changed in that commits).

**Comment by lambdalisue** [comment]
I'll check this when I finished to write behavior tests of exiting commands 👍

**Comment by lambdalisue** [comment]
Done in #16
