### ISSUE TITLE
support visualstudio.com git repositories

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#71]
It would be great if `https://*.visualstudio.com` repositories were supported so `:Gina browse` just works. This one uses subdomain unlike github and bitbucket.

Pattern for `_` (repository base)
https://prabirshrestha.visualstudio.com/{reponame}
https://prabirshrestha.visualstudio.com/{team}/{reponame}

looks like these where `{reponame}` is the name of the repository and `{team}` is the name of the team. Team name is optional. It can also contain n number of `/`.

Pattern for `root`: (file viewer)
https://prabirshrestha.visualstudio.com/_git/{reponame}
https://prabirshrestha.visualstudio.com/{team}/{reponame}

**Comment by lambdalisue** [comment]
You can add your own repository types to `g:gina#command#branch#translation_patterns` (https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/command/browse.vim#L132)

The format documentations are https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L2406
https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L1933

If you think this setting should be a builtin, please send me a PR 👍

**Comment by lambdalisue** [comment]
So any update?

**Comment by prabirshrestha** [comment]
Haven't looked into it yet since this isn't a blocker for me but rather a nice to have feature. In the meantime if you think this is a noise feel free to close.

**Comment by prabirshrestha** [comment]
@lambdalisue So I did get this working but would it be possible to support wildcard domains? I would like to avoid having the same mapping for `office.visualstudio.com`, `windows.visualstudio.com`, `msazure.visualstudio.com`. If wildcard is supported we could this as pattern in gina.vim without custom vimrc.

```vim
call extend(g:gina#command#browse#translation_patterns, {
    \ 'msazure.visualstudio.com': [
    \   [
    \       '\vhttps?://(%domain)/(.{-})/_git/(.{-})$'
    \   ],
    \   {
    \       '_': 'https://\1/\2/_git/\3/?path=%pt&version=GB%r0',
    \       'root': 'https://\1/\2/_git/\3/?version=GB%r0',
    \   }
    \ ]
    \ })
```

**Comment by lambdalisue** [comment]
Sorry for late. I have not tried yet but it seems the key of the dictionary is used as a raw pattern string (unexpectedly) so `'.*\.visualstudio\.com'` may work.

https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/command/browse.vim#L147-L159

**Comment by prabirshrestha** [comment]
It does seem to work. Would it be possible to ship those settings as part of gina.vim?

```vim
call extend(g:gina#command#browse#translation_patterns, {
    \ '.*\.visualstudio\.com': [
    \   [
    \       '\vhttps?://(%domain)/(.{-})/_git/(.{-})$'
    \   ],
    \   {
    \       '_': 'https://\1/\2/_git/\3/?path=%pt&version=GB%r0',
    \       'root': 'https://\1/\2/_git/\3/?version=GB%r0',
    \   }
    \ ]
    \ })
```

**Comment by lambdalisue** [comment]
Please send me PR 👍

**Comment by lambdalisue** [comment]
#195
