### ISSUE TITLE
change blame window

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#72]
Is it possible to configure the blame window to show as @mhartington suggested instead? Usually I'm interested in who changed the file and when.

![image](https://cloud.githubusercontent.com/assets/2835826/23377868/76a77e7e-fcff-11e6-8bef-bfc28e02dda2.png)

**Comment by lambdalisue** [comment]
So you prefer

```
{author} {when} {SHA1 Indicator} | Line.....
```

instead of

```
{Summary} {when} {SHA1 indicator} | Line ...
```

right? It is not supported. You need to send me a PR to enable that kind of output.

**Comment by lambdalisue** [comment]
I added `--use-author-instead` option to `:Gina blame`. It solved your issue right?

![screenshot 2017-04-03 07 45 49](https://cloud.githubusercontent.com/assets/546312/24591651/d5712484-1841-11e7-91f4-e4c7d2bee6f3.png)

Usage: `:Gina blame --use-author-instead {treeish}`

**Comment by tracyone** [comment]
good job

**Comment by mhartington** [comment]
Looks great! Most times when I blame a file, I'm looking for the author first, not the commit 😄

**Comment by prabirshrestha** [comment]
@lambdalisue Looks great. Overtime I will know if I still miss the commit hash. Currently I'm using `Tab`, `:action` and repeat with `.`. If I do need it I will file another issue.
