### ISSUE TITLE
what is the best way to quit gina blame

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#78]
Currently when I use `:Gina blame` it shows the following UI.

I then use `:q` on the left and `:bd` on the right pane. Is there a mapping I can setup so that `q` can close both at the same time?

![image](https://cloud.githubusercontent.com/assets/287744/24809873/1bd832ba-1b75-11e7-9936-991b45a54006.png)

**Comment by lambdalisue** [comment]
If you close the right buffer (a content buffer) with `:q`, both window should be closed. If you close the left buffer (a navigation buffer), the right buffer remains for further operations.

If you feel this behavior is not enough for your usage, please explain the detail idea for the behavior and I'll consider 👍  or if you feel it is enough, just close this issue please.

**Comment by bimlas** [comment]
Closing content window with `:q` not works for me, tried out with `:bdelete` too: it's closing the content window, but blame window remains open (as the only one window).

I think an "exit from entire blame" mapping / ~command~ action would be useful.

**Comment by bimlas** [comment]
Opened #79 to add a mapping to exit from entire blame session.

**Comment by lambdalisue** [comment]
Sorry for late reply. Well probably closing is working as my expectation. The current implementation is

1. Close both buffers if there are more than **three** windows
2. Close a single buffer if there are exactly two windows while gina doesn't know what is the best way (quitting Vim or open a new buffer)

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/gina.vim/commit/da85b1953833033df358da43d88a0d894608d8ce
