### ISSUE TITLE
Gina show --opener=edit : fail on some file.

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#80]
`:Gina blame :` results in (when editing project.clj):

```
Fail: env GIT_TERMINAL_PROMPT=0 git --no-pager -c core.editor=false -c color.status=always -C /home/dominic/src/github.com/software-foo/foo show --opener=edit --group=blame-body --line=1 :pro
ject.clj                                                                                                                                                                                            
fatal: unrecognized argument: --opener=edit
```

**Comment by lambdalisue** [comment]
I could not reproduce the situation

1. Which OS and version do you use?
2. Which Vim/Neovim do you use?
3. Whch revision of gina do you use?
4. How to reproduce that? A step by step procedure would be nice
5. Did you try it with a minimal vimrc? A vimrc less than 50 lines is nice

**Comment by SevereOverfl0w** [comment]
I can answer some now, will come back with 5 later.

1. Arch Linux
2. NVIM v0.2.0-1303-gdd391bfc
3. commit: 01e6597280346dac9f0261df58926e9b6f22fabc
4. Opened `project.clj`, ran `:Gina blame :`

**Comment by SevereOverfl0w** [comment]
Hmm, seems to be related to the particular project I'm on. I hadn't tried in a different repo: it works there!

**Comment by SevereOverfl0w** [comment]
It's a problem that is particular to `project.clj` file. Other files work fine. Sorry, I hadn't dug in deep (I figured it might be a simple mistake, not an edge case!)

I can reproduce this on: https://github.com/juxt/bidi via `:Gina blame :` with `project.clj` open.

**Comment by lambdalisue** [comment]
I could reproduce the situation with project.clj on juxt/bidi with `:Gina show --opener=edit :`. I'll investigate.

**Comment by lambdalisue** [comment]
I've tried to investigate the problem but I have no idea why for now... It seems args.pop('--opener') somehow fail.

It would take time to fix this.

**Comment by lambdalisue** [comment]
Finally I got the reason. I'll fix this soon.

**Comment by lambdalisue** [comment]
Could you check #81

**Comment by SevereOverfl0w** [comment]
That branch resolves my issue, thanks!
