### ISSUE TITLE
treeish causes (sometimes) unwanted file-based autocmds

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#82]
It's a common idiom to do: `aucmd BufEnter *.clj …` in plugins. For a blame buffer `gina://project:blame/:project.clj`. This is useful for `show` type, but not for the `:blame` window.

Given this, is it worthwhile adding a suffix of some kind to _some_ types, e.g. `gina://project:blame/:project.clj/noaucmd`? That would prevent aucmds for those types.

**Comment by bimlas** [comment]
Why don't you add autocommand to filetype (`autocmd Filetype clojure ...`) or extend the `BufEnter` with `autocmd BufEnter *.clj if &filetype == 'clojure' | ... | endif`. Disabling autocommands would break Gina itself: try out `:noautocmd Gina blame :`.

**Comment by SevereOverfl0w** [comment]
Sorry, I can see the confusion based on my suggestion. This would also work: `gina://project:blame/:project.clj/foobar`. The intent is to prevent the common `*.clj` from kicking in, not to block all autocmds.

Checking the filetype may be a sufficient suggestion for user-defined autocmds, but not for plugins, unaware of the restriction.

**Comment by SevereOverfl0w** [comment]
Some of the issue I am seeing may be due to changing the filetype (now I dig a little deeper into what plugins are doing!). For example:

https://github.com/guns/vim-clojure-static/blob/master/ftdetect/clojure.vim

Does a `BufNewFile *.clj` to set the filetype. I'm guessing all the FileType aucmds kick in for _clojure_ (e.g. calling ftplugin/clojure.vim). Then gina alters the filetype to the correct one.

Useful for `show`, as it kicks in syntax highlighting & sets up navigational mappings. Bad for `blame`  as those autocmds could be setting up potentially dangerous things.

**Comment by bimlas** [comment]
OK, got your problem.

Just tried out [tpope/vim-fugitive](https://github.com/tpope/vim-fugitive) to see what's happening there: the navigation window has `.fugitiveblame` extension.

Disabling the autocommands only for the navi would be enough and there is an [`eventignore` setting](http://vimdoc.sourceforge.net/htmldoc/options.html#'eventignore') which makes it possible, but the code would become seriously fragile so I vote for changing the navi buffer's name to prevent executing of filetype autocommands.

**Comment by lambdalisue** [comment]
Hum... I understand the situation. However, I still feel that is a bad behavior of plugins which use BufEnter.

Could you give me more examples to convince me?

**Comment by bimlas** [comment]
`BufEnter` is used for filetype detection:
* http://vimdoc.sourceforge.net/htmldoc/filetype.html#new-filetype
* https://github.com/vim/vim/blob/39170e2d9761345df4be67d4d3928ac1094b9adf/runtime/filetype.vim#L509-L510

**Comment by bimlas** [comment]
Sorry, misread it: you're right, that plugin should use `BufNewFile,BufRead`.

**Comment by SevereOverfl0w** [comment]
Worth noting that the plugins I use do: `BufNewFile,BufRead` for filetype detection (more extensive that that included in vim) and then the plugins bringing in mappings _are_ using `FileType` for their autocmds. But the mappings created by the FileType plugins are being introduced into the blame buffer.

**Comment by lambdalisue** [comment]
Well I'm not sure if Vim automatically call that but there is `b:undo_ftplugin` 

```
UNDO						*undo_indent* *undo_ftplugin*

When the user does ":setfiletype xyz" the effect of the previous filetype
should be undone.  Set the b:undo_ftplugin variable to the commands that will
undo the settings in your filetype plugin.  Example: >

	let b:undo_ftplugin = "setlocal fo< com< tw< commentstring<"
		\ . "| unlet b:match_ignorecase b:match_words b:match_skip"

Using ":setlocal" with "<" after the option name resets the option to its
global value.  That is mostly the best way to reset the option value.
```

So it is more likely issues on those ftplugins I guess.
