### ISSUE TITLE
Blame does not factor in sign column width

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#83]
If you have a sign column enabled globally [via dummy](https://github.com/haya14busa/vim-signjk-motion/blob/5501c4892851628e0f88dd3f1deb3210cff2201a/plugin/signjk.vim#L44-L47) then you will have a sign column in the blame buffer. This causes the width calculation to be off slightly (not showing the colours).

Not sure if this can be resolved. I'll likely implement my own, "aware" dummy column, or disable it outright, as this is perhaps a misuse. But I thought I'd ask anyway.

**Comment by lambdalisue** [comment]
Probably your issue is fixed. Could you try #84?

**Comment by SevereOverfl0w** [comment]
That does indeed resolve it, thanks for the speedy fix!

**Comment by lambdalisue** [comment]
Good. I'll merge that after CI success.
