### ISSUE TITLE
Navigation window width doesn't update

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdalisue/gina.vim#85]
Another one that  _may_ be expected behaviour. Sorry for the many issues.

Doing `:Gina blame :` followed by `:Gina blame --width 50 :` doesn't resize the Navigation window. A nice feature would be if it didn't use the default when unspecfied, if it is already open.  So if I manually resize (via `Ctrl-W >`) and then call `:Gina blame :` the navigation window stays the same width.

**Comment by lambdalisue** [comment]
No worry. Descriptive issues are welcome.

Does `:Gina blame --width=10 :` helps?

**Comment by SevereOverfl0w** [comment]
No, same issue. I think I may not have explained it well.

If I do:
1) `:Gina blame :`
2) `:Gina blame --width=50 :`

At "2" the Navigation Buffer does not become width 50, but stays the same.

**Comment by lambdalisue** [comment]
Sorry for late. Hum, currently gina does not touch the window width of existing window.
It would be nice and I would like to introduce such feature so please wait or send me PR 👍
