### ISSUE TITLE
Gina push when cloned with https

### ISSUE THREAD

**Issue by monkoose** [lambdalisue/gina.vim#86]
`Gina push` command returns this error message `[gina] fatal: could not read Username for 'https://github.com': terminal prompts disabled`
So it is impossible to push.
Any help?

`neovim 0.1.7` 
`Archlinux`

**Comment by lambdalisue** [comment]
- Install "ssh-askpass-gnome" and configure it properly
- Or Install "zenity"

https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L2439

**Comment by monkoose** [comment]
@lambdalisue Thank you. It works.
And sorry for bothering, completely missed this part from the documentation.
