### ISSUE TITLE
Gina blame keeping the scroll position

### ISSUE THREAD

**Issue by itchyny** [lambdalisue/gina.vim#87]
This is a question, how can I keep the scroll position on `:Gina blame :`? I always want to see the histories around the cursor.

**Comment by lambdalisue** [comment]
Sorry. I don't get your question.
具体的な例を教えていただけませんか？

**Comment by itchyny** [comment]
<img src="https://cloud.githubusercontent.com/assets/375258/25468705/a48662b6-2b52-11e7-8b06-fdcba2e359d5.gif">
As you see in the above screenshot, I always scroll to the the line I was.

**Comment by lambdalisue** [comment]
1. `:Gina blame --line=10 :` opens buffers and move cursors to line 10
2. `:Gina blame :` automatically guess current cursor position

So gina should open blame windows as you want like
 
![](http://g.recordit.co/no47vsRhyi.gif)

The gif was took several minutes ago with macOS Sierra on Neovim 0.1.7 with latest gina.

it seems there are some bug on your env. Could you give me

1. Detail about your environment (OS, Vim version, gina version, etc)
2. If possible, minimum vimrc

**Comment by bimlas** [comment]
I think he (she?) likes to get this behaviour:
https://github.com/lambdalisue/gina.vim/pull/45#issuecomment-283892091:
> Blame on the currently blamed content (`<CR>` on the marked line) should set cursor's position to the same line

The answer for this is:
https://github.com/lambdalisue/gina.vim/pull/45#issuecomment-283918360

**EDIT**

Sorry, I misunderstood the issue, forget my comment.

**Comment by itchyny** [comment]
Okay. I found that https://github.com/lambdalisue/gina.vim/blob/01e6597280346dac9f0261df58926e9b6f22fabc/autoload/gina/core/args.vim#L100 has some issues.
```
cd /path/to/gina.vim
vi autoload/gina/util.vim
:lcd %:p:h
G
:Gina blame :
```
After some debugging I found that `echom string([treeish1 , treeish2])` prints `[':util.vim', ':autoload/gina/util.vim']`, which results to `args.params.line = v:null`. I think the code does not work when current directory is not at the git root.

**Comment by lambdalisue** [comment]
Oh... Again... Sorry for that.
I'll fix thank you!
