### ISSUE TITLE
Yank commit hash in blame window

### ISSUE THREAD

**Issue by itchyny** [lambdalisue/gina.vim#88]
How can I yank the commit hash at the cursor? I looked into the document but in vain.

**Comment by lambdalisue** [comment]
I'm sorry. There is no such action for now (See https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/action/blame.vim)

PR is welcome 👍

**Comment by itchyny** [comment]
Okay, thanks for your response.

**Comment by lambdalisue** [comment]
Note this: https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/util.vim#L62

**Comment by bimlas** [comment]
Opened #93

**Comment by lambdalisue** [comment]
Fixed by #106
