### ISSUE TITLE
Blame: is_sign_visible(): E158 invalid buffer name

### ISSUE THREAD

**Issue by jlebray** [lambdalisue/gina.vim#91]
Hi,

I got an issue with the blame command and the modifications made in #84 
Whenever I press Return on a blame line I get this error :
![image](https://cloud.githubusercontent.com/assets/15625131/25630057/11aeb204-2f6c-11e7-8409-2ee0aea540bf.png)
(It translates to error detected while processing ... E158: Invalid buffer name)

I'm using the last release of Neovim (v0.2.0)

**Comment by bimlas** [comment]
What's the steps of reproducing the problem?

It seems to be a bug, because 0 points to alternate (previous) buffer instead of the current one. Can you try out #92 please?

**Comment by jlebray** [comment]
It happened whenever I pressed Return on a blame line, after opening the blame split with "Gina blame :"
#92 Fixed the problem, thanks !

**Comment by lambdalisue** [comment]
Thanks @bimlas for quick fix!
