### ISSUE TITLE
include both author and commit hash in blame window

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#96]
Continuation of https://github.com/lambdalisue/gina.vim/issues/72.

While `:Gina blame --use-author-instead {treeish}` is now supported which includes author, after using using it for couple of week I noticed that I still prefer to have both the hash and author in the left blame window. Primarily because if files are separated by feature there could only be one person modifying and all the modifications could had happened 1 week ago and there is no way to know what actually changed without the commit hash.

It would be also good to set a custom format for date time instead of human friendly date time (1 week ago). Let me know if you want me to file this as a separate issue.

**Comment by lambdalisue** [comment]
Got it. Give me time. Ping me if I don't reply until the second weekend of June

**Comment by lambdalisue** [comment]
`--use-author-instead` is removed. Use `--format` like

```
:Gina blame --format="%su by %au%=%ti%ma%in"
```

where

- `%su` is summary
- `%au` is author
- `%ti` is timestamp
- `%ma` is marker
- `%in` is index
- `%=` is separator (lhs and rhs is separated here)

<img width="1920" alt="screen shot 2017-08-02 at 21 18 10" src="https://user-images.githubusercontent.com/546312/28873316-1e2d142c-77c8-11e7-8d0d-9dd8d3491b37.png">
