### ISSUE TITLE
Gina checkout && Gina merge support

### ISSUE THREAD

**Issue by wsdjeg** [lambdalisue/gina.vim#97]
hi @lambdalisue I hope gina support git checkout and git merge command.

**Comment by lambdalisue** [comment]
What did you mean exactly? The followings works and I'm OK with these.

```
:Gina checkout HEAD -- autoload/gina.vim

:Gina merge dev
```

**Comment by wsdjeg** [comment]
@lambdalisue ohh, sorry, I do not know gina support merge and checkout command,  but I can not complete `merge` and `checkout` after `:Gina `

**Comment by lambdalisue** [comment]
Well... did you mean by something

```
:Gina merge ... | Gina checkout ...
```

or whatever? Then gina does not support `|`. There are two options.

1. Define a new command with `-bar`. Ref https://github.com/lambdalisue/vim-gita/blob/master/doc/gita.txt#L1841-L1857

2. Create a function to execute both command like

```
function GinaMergeCheckout() abort
    Gina merge ...whatever
   Gina checkout ...whatever
endfunction
" then
call GinaMergeCheckout
```

**Comment by wsdjeg** [comment]
no, I mean, compete `merge` after `:Gina`,  just press `<Tab>` after `:Gina m` and complete branch name after `:Gina merge`

**Comment by lambdalisue** [comment]
I see. It is not supported and currently no plan to support it. While git have too many commands and arguments, command completions are supported only for gina's commands but git's commands

**Comment by wsdjeg** [comment]
ok, I see, and I am ok with it. Thanks!
